// This file is auto-generated by @hey-api/openapi-ts

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: 'password'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const HostCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        ipv4_address: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ipv4 Address'
        },
        ipv6_address: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ipv6 Address'
        },
        secret_key: {
            type: 'string',
            maxLength: 255,
            title: 'Secret Key'
        },
        welcome_banner: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Welcome Banner'
        },
        reject_banner: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reject Banner'
        },
        motd_banner: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Motd Banner'
        },
        failed_authentication_banner: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Failed Authentication Banner'
        },
        parent: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['name', 'secret_key'],
    title: 'HostCreate'
} as const;

export const HostPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        ipv4_address: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ipv4 Address'
        },
        ipv6_address: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ipv6 Address'
        },
        secret_key: {
            type: 'string',
            maxLength: 255,
            title: 'Secret Key'
        },
        welcome_banner: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Welcome Banner'
        },
        reject_banner: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reject Banner'
        },
        motd_banner: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Motd Banner'
        },
        failed_authentication_banner: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Failed Authentication Banner'
        },
        parent: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['name', 'secret_key', 'id', 'created_at'],
    title: 'HostPublic'
} as const;

export const HostUpdateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        ipv4_address: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ipv4 Address'
        },
        ipv6_address: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ipv6 Address'
        },
        secret_key: {
            type: 'string',
            maxLength: 255,
            title: 'Secret Key'
        },
        welcome_banner: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Welcome Banner'
        },
        reject_banner: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reject Banner'
        },
        motd_banner: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Motd Banner'
        },
        failed_authentication_banner: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Failed Authentication Banner'
        },
        parent: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parent'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['name', 'secret_key'],
    title: 'HostUpdate'
} as const;

export const HostsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/HostPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'HostsPublic'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id', 'created_at'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const MavisPublicSchema = {
    properties: {
        ldap_server_type: {
            type: 'string',
            title: 'Ldap Server Type',
            default: 'openldap'
        },
        ldap_hosts: {
            type: 'string',
            title: 'Ldap Hosts',
            default: 'ldaps://ldap-server'
        },
        ldap_base: {
            type: 'string',
            title: 'Ldap Base',
            default: 'dc=example,dc=com'
        },
        ldap_user: {
            type: 'string',
            title: 'Ldap User',
            default: 'cn=admin,dc=example,dc=com'
        },
        ldap_passwd: {
            type: 'string',
            title: 'Ldap Passwd',
            default: 'admin_password'
        },
        ldap_filter: {
            type: 'string',
            title: 'Ldap Filter',
            default: '(objectClass=person)'
        },
        ldap_timeout: {
            type: 'integer',
            title: 'Ldap Timeout',
            default: 5
        },
        require_tacacs_group_prefix: {
            type: 'integer',
            title: 'Require Tacacs Group Prefix',
            default: 0
        },
        tacacs_group_prefix: {
            type: 'string',
            title: 'Tacacs Group Prefix',
            default: 'tacacs_'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'created_at'],
    title: 'MavisPublic'
} as const;

export const MavisUpdateSchema = {
    properties: {
        ldap_server_type: {
            type: 'string',
            title: 'Ldap Server Type',
            default: 'openldap'
        },
        ldap_hosts: {
            type: 'string',
            title: 'Ldap Hosts',
            default: 'ldaps://ldap-server'
        },
        ldap_base: {
            type: 'string',
            title: 'Ldap Base',
            default: 'dc=example,dc=com'
        },
        ldap_user: {
            type: 'string',
            title: 'Ldap User',
            default: 'cn=admin,dc=example,dc=com'
        },
        ldap_passwd: {
            type: 'string',
            title: 'Ldap Passwd',
            default: 'admin_password'
        },
        ldap_filter: {
            type: 'string',
            title: 'Ldap Filter',
            default: '(objectClass=person)'
        },
        ldap_timeout: {
            type: 'integer',
            title: 'Ldap Timeout',
            default: 5
        },
        require_tacacs_group_prefix: {
            type: 'integer',
            title: 'Require Tacacs Group Prefix',
            default: 0
        },
        tacacs_group_prefix: {
            type: 'string',
            title: 'Tacacs Group Prefix',
            default: 'tacacs_'
        }
    },
    type: 'object',
    title: 'MavisUpdate'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const ProfileCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        action: {
            type: 'string',
            maxLength: 255,
            title: 'Action'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['name', 'action'],
    title: 'ProfileCreate'
} as const;

export const ProfilePublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        action: {
            type: 'string',
            maxLength: 255,
            title: 'Action'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['name', 'action', 'id', 'created_at'],
    title: 'ProfilePublic'
} as const;

export const ProfileScriptCreateSchema = {
    properties: {
        condition: {
            type: 'string',
            maxLength: 255,
            title: 'Condition'
        },
        key: {
            type: 'string',
            maxLength: 255,
            title: 'Key'
        },
        value: {
            type: 'string',
            maxLength: 255,
            title: 'Value'
        },
        action: {
            type: 'string',
            maxLength: 255,
            title: 'Action'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        profile_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Profile Id'
        }
    },
    type: 'object',
    required: ['condition', 'key', 'value', 'action'],
    title: 'ProfileScriptCreate'
} as const;

export const ProfileScriptPublicSchema = {
    properties: {
        condition: {
            type: 'string',
            maxLength: 255,
            title: 'Condition'
        },
        key: {
            type: 'string',
            maxLength: 255,
            title: 'Key'
        },
        value: {
            type: 'string',
            maxLength: 255,
            title: 'Value'
        },
        action: {
            type: 'string',
            maxLength: 255,
            title: 'Action'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        profile_id: {
            type: 'string',
            format: 'uuid',
            title: 'Profile Id'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        profile_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Profile Name'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['condition', 'key', 'value', 'action', 'profile_id', 'id', 'created_at'],
    title: 'ProfileScriptPublic'
} as const;

export const ProfileScriptSetCreateSchema = {
    properties: {
        key: {
            type: 'string',
            maxLength: 255,
            title: 'Key'
        },
        value: {
            type: 'string',
            title: 'Value'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        profilescript_id: {
            type: 'string',
            format: 'uuid',
            title: 'Profilescript Id'
        }
    },
    type: 'object',
    required: ['key', 'value', 'profilescript_id'],
    title: 'ProfileScriptSetCreate'
} as const;

export const ProfileScriptSetPublicSchema = {
    properties: {
        key: {
            type: 'string',
            maxLength: 255,
            title: 'Key'
        },
        value: {
            type: 'string',
            title: 'Value'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        profilescript_id: {
            type: 'string',
            format: 'uuid',
            title: 'Profilescript Id'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        profile_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Profile Id'
        },
        profile_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Profile Name'
        },
        profilescript_block: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Profilescript Block'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['key', 'value', 'profilescript_id', 'id', 'created_at'],
    title: 'ProfileScriptSetPublic'
} as const;

export const ProfileScriptSetUpdateSchema = {
    properties: {
        key: {
            type: 'string',
            maxLength: 255,
            title: 'Key'
        },
        value: {
            type: 'string',
            title: 'Value'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        profilescript_id: {
            type: 'string',
            format: 'uuid',
            title: 'Profilescript Id'
        }
    },
    type: 'object',
    required: ['key', 'value', 'profilescript_id'],
    title: 'ProfileScriptSetUpdate'
} as const;

export const ProfileScriptSetsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ProfileScriptSetPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ProfileScriptSetsPublic'
} as const;

export const ProfileScriptUpdateSchema = {
    properties: {
        condition: {
            type: 'string',
            maxLength: 255,
            title: 'Condition'
        },
        key: {
            type: 'string',
            maxLength: 255,
            title: 'Key'
        },
        value: {
            type: 'string',
            maxLength: 255,
            title: 'Value'
        },
        action: {
            type: 'string',
            maxLength: 255,
            title: 'Action'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        profile_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Profile Id'
        }
    },
    type: 'object',
    required: ['condition', 'key', 'value', 'action'],
    title: 'ProfileScriptUpdate'
} as const;

export const ProfileScriptsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ProfileScriptPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ProfileScriptsPublic'
} as const;

export const ProfileUpdateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        action: {
            type: 'string',
            maxLength: 255,
            title: 'Action'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['name', 'action'],
    title: 'ProfileUpdate'
} as const;

export const ProfilesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ProfilePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ProfilesPublic'
} as const;

export const RulesetCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        enabled: {
            type: 'string',
            title: 'Enabled',
            default: 'yes'
        },
        action: {
            type: 'string',
            maxLength: 255,
            title: 'Action'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['name', 'action'],
    title: 'RulesetCreate'
} as const;

export const RulesetPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        enabled: {
            type: 'string',
            title: 'Enabled',
            default: 'yes'
        },
        action: {
            type: 'string',
            maxLength: 255,
            title: 'Action'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['name', 'action', 'id', 'created_at'],
    title: 'RulesetPublic'
} as const;

export const RulesetScriptCreateSchema = {
    properties: {
        condition: {
            type: 'string',
            maxLength: 255,
            title: 'Condition'
        },
        key: {
            type: 'string',
            maxLength: 255,
            title: 'Key'
        },
        value: {
            type: 'string',
            maxLength: 255,
            title: 'Value'
        },
        action: {
            type: 'string',
            maxLength: 255,
            title: 'Action'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        ruleset_id: {
            type: 'string',
            format: 'uuid',
            title: 'Ruleset Id'
        }
    },
    type: 'object',
    required: ['condition', 'key', 'value', 'action', 'ruleset_id'],
    title: 'RulesetScriptCreate'
} as const;

export const RulesetScriptPublicSchema = {
    properties: {
        condition: {
            type: 'string',
            maxLength: 255,
            title: 'Condition'
        },
        key: {
            type: 'string',
            maxLength: 255,
            title: 'Key'
        },
        value: {
            type: 'string',
            maxLength: 255,
            title: 'Value'
        },
        action: {
            type: 'string',
            maxLength: 255,
            title: 'Action'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        ruleset_id: {
            type: 'string',
            format: 'uuid',
            title: 'Ruleset Id'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        ruleset_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ruleset Name'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['condition', 'key', 'value', 'action', 'ruleset_id', 'id', 'created_at'],
    title: 'RulesetScriptPublic'
} as const;

export const RulesetScriptSetCreateSchema = {
    properties: {
        key: {
            type: 'string',
            maxLength: 255,
            title: 'Key'
        },
        value: {
            type: 'string',
            maxLength: 255,
            title: 'Value'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        rulesetscript_id: {
            type: 'string',
            format: 'uuid',
            title: 'Rulesetscript Id'
        }
    },
    type: 'object',
    required: ['key', 'value', 'rulesetscript_id'],
    title: 'RulesetScriptSetCreate'
} as const;

export const RulesetScriptSetPublicSchema = {
    properties: {
        key: {
            type: 'string',
            maxLength: 255,
            title: 'Key'
        },
        value: {
            type: 'string',
            maxLength: 255,
            title: 'Value'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        rulesetscript_id: {
            type: 'string',
            format: 'uuid',
            title: 'Rulesetscript Id'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        ruleset_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ruleset Id'
        },
        ruleset_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ruleset Name'
        },
        rulesetscript_block: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Rulesetscript Block'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['key', 'value', 'rulesetscript_id', 'id', 'created_at'],
    title: 'RulesetScriptSetPublic'
} as const;

export const RulesetScriptSetUpdateSchema = {
    properties: {
        key: {
            type: 'string',
            maxLength: 255,
            title: 'Key'
        },
        value: {
            type: 'string',
            maxLength: 255,
            title: 'Value'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        rulesetscript_id: {
            type: 'string',
            format: 'uuid',
            title: 'Rulesetscript Id'
        }
    },
    type: 'object',
    required: ['key', 'value', 'rulesetscript_id'],
    title: 'RulesetScriptSetUpdate'
} as const;

export const RulesetScriptSetsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/RulesetScriptSetPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'RulesetScriptSetsPublic'
} as const;

export const RulesetScriptUpdateSchema = {
    properties: {
        condition: {
            type: 'string',
            maxLength: 255,
            title: 'Condition'
        },
        key: {
            type: 'string',
            maxLength: 255,
            title: 'Key'
        },
        value: {
            type: 'string',
            maxLength: 255,
            title: 'Value'
        },
        action: {
            type: 'string',
            maxLength: 255,
            title: 'Action'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        ruleset_id: {
            type: 'string',
            format: 'uuid',
            title: 'Ruleset Id'
        }
    },
    type: 'object',
    required: ['condition', 'key', 'value', 'action', 'ruleset_id'],
    title: 'RulesetScriptUpdate'
} as const;

export const RulesetScriptsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/RulesetScriptPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'RulesetScriptsPublic'
} as const;

export const RulesetUpdateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        enabled: {
            type: 'string',
            title: 'Enabled',
            default: 'yes'
        },
        action: {
            type: 'string',
            maxLength: 255,
            title: 'Action'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['name', 'action'],
    title: 'RulesetUpdate'
} as const;

export const RulesetsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/RulesetPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'RulesetsPublic'
} as const;

export const TacacsConfigCreateSchema = {
    properties: {
        filename: {
            type: 'string',
            maxLength: 30,
            title: 'Filename'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['filename'],
    title: 'TacacsConfigCreate'
} as const;

export const TacacsConfigPreviewPublicSchema = {
    properties: {
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        data: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data'
        }
    },
    type: 'object',
    required: ['created_at'],
    title: 'TacacsConfigPreviewPublic'
} as const;

export const TacacsConfigPublicSchema = {
    properties: {
        filename: {
            type: 'string',
            maxLength: 255,
            title: 'Filename'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        active: {
            type: 'boolean',
            title: 'Active'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        data: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data'
        }
    },
    type: 'object',
    required: ['filename', 'id', 'active', 'created_at'],
    title: 'TacacsConfigPublic'
} as const;

export const TacacsConfigUpdateSchema = {
    properties: {
        filename: {
            type: 'string',
            maxLength: 255,
            title: 'Filename'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['filename'],
    title: 'TacacsConfigUpdate'
} as const;

export const TacacsConfigsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/TacacsConfigPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'TacacsConfigsPublic'
} as const;

export const TacacsGroupCreateSchema = {
    properties: {
        group_name: {
            type: 'string',
            maxLength: 255,
            title: 'Group Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['group_name'],
    title: 'TacacsGroupCreate'
} as const;

export const TacacsGroupPublicSchema = {
    properties: {
        group_name: {
            type: 'string',
            maxLength: 255,
            title: 'Group Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['group_name', 'id', 'created_at'],
    title: 'TacacsGroupPublic'
} as const;

export const TacacsGroupUpdateSchema = {
    properties: {
        group_name: {
            type: 'string',
            maxLength: 255,
            title: 'Group Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['group_name'],
    title: 'TacacsGroupUpdate'
} as const;

export const TacacsGroupsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/TacacsGroupPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'TacacsGroupsPublic'
} as const;

export const TacacsLogPublicSchema = {
    properties: {
        filename: {
            type: 'string',
            maxLength: 255,
            title: 'Filename'
        },
        filepath: {
            type: 'string',
            maxLength: 1024,
            title: 'Filepath'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        data: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Data'
        }
    },
    type: 'object',
    required: ['filename', 'filepath', 'id'],
    title: 'TacacsLogPublic'
} as const;

export const TacacsLogsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/TacacsLogPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'TacacsLogsPublic'
} as const;

export const TacacsNgSettingPublicSchema = {
    properties: {
        ipv4_enabled: {
            type: 'boolean',
            title: 'Ipv4 Enabled',
            default: true
        },
        ipv4_address: {
            type: 'string',
            title: 'Ipv4 Address',
            default: '0.0.0.0'
        },
        ipv4_port: {
            type: 'integer',
            title: 'Ipv4 Port',
            default: 49
        },
        ipv6_enabled: {
            type: 'boolean',
            title: 'Ipv6 Enabled',
            default: false
        },
        ipv6_address: {
            type: 'string',
            title: 'Ipv6 Address',
            default: '::'
        },
        ipv6_port: {
            type: 'integer',
            title: 'Ipv6 Port',
            default: 49
        },
        instances_min: {
            type: 'integer',
            title: 'Instances Min',
            default: 1
        },
        instances_max: {
            type: 'integer',
            title: 'Instances Max',
            default: 10
        },
        background: {
            type: 'string',
            title: 'Background',
            default: 'no'
        },
        access_logfile_destination: {
            type: 'string',
            title: 'Access Logfile Destination',
            default: '/app/tacacs_config_and_logs/log/%Y/%m/access-%m-%d-%Y.txt'
        },
        accounting_logfile_destination: {
            type: 'string',
            title: 'Accounting Logfile Destination',
            default: '/app/tacacs_config_and_logs/log/%Y/%m/accounting-%m-%d-%Y.txt'
        },
        authentication_logfile_destination: {
            type: 'string',
            title: 'Authentication Logfile Destination',
            default: '/app/tacacs_config_and_logs/log/%Y/%m/authentication-%m-%d-%Y.txt'
        },
        login_backend: {
            type: 'string',
            title: 'Login Backend',
            default: 'mavis'
        },
        user_backend: {
            type: 'string',
            title: 'User Backend',
            default: 'mavis'
        },
        pap_backend: {
            type: 'string',
            title: 'Pap Backend',
            default: 'mavis'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'created_at'],
    title: 'TacacsNgSettingPublic'
} as const;

export const TacacsNgSettingUpdateSchema = {
    properties: {
        ipv4_enabled: {
            type: 'boolean',
            title: 'Ipv4 Enabled',
            default: true
        },
        ipv4_address: {
            type: 'string',
            title: 'Ipv4 Address',
            default: '0.0.0.0'
        },
        ipv4_port: {
            type: 'integer',
            title: 'Ipv4 Port',
            default: 49
        },
        ipv6_enabled: {
            type: 'boolean',
            title: 'Ipv6 Enabled',
            default: false
        },
        ipv6_address: {
            type: 'string',
            title: 'Ipv6 Address',
            default: '::'
        },
        ipv6_port: {
            type: 'integer',
            title: 'Ipv6 Port',
            default: 49
        },
        instances_min: {
            type: 'integer',
            title: 'Instances Min',
            default: 1
        },
        instances_max: {
            type: 'integer',
            title: 'Instances Max',
            default: 10
        },
        background: {
            type: 'string',
            title: 'Background',
            default: 'no'
        },
        access_logfile_destination: {
            type: 'string',
            title: 'Access Logfile Destination',
            default: '/app/tacacs_config_and_logs/log/%Y/%m/access-%m-%d-%Y.txt'
        },
        accounting_logfile_destination: {
            type: 'string',
            title: 'Accounting Logfile Destination',
            default: '/app/tacacs_config_and_logs/log/%Y/%m/accounting-%m-%d-%Y.txt'
        },
        authentication_logfile_destination: {
            type: 'string',
            title: 'Authentication Logfile Destination',
            default: '/app/tacacs_config_and_logs/log/%Y/%m/authentication-%m-%d-%Y.txt'
        },
        login_backend: {
            type: 'string',
            title: 'Login Backend',
            default: 'mavis'
        },
        user_backend: {
            type: 'string',
            title: 'User Backend',
            default: 'mavis'
        },
        pap_backend: {
            type: 'string',
            title: 'Pap Backend',
            default: 'mavis'
        }
    },
    type: 'object',
    title: 'TacacsNgSettingUpdate'
} as const;

export const TacacsServiceCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'TacacsServiceCreate'
} as const;

export const TacacsServicePublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['name', 'id', 'created_at'],
    title: 'TacacsServicePublic'
} as const;

export const TacacsServiceUpdateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'TacacsServiceUpdate'
} as const;

export const TacacsServicesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/TacacsServicePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'TacacsServicesPublic'
} as const;

export const TacacsUserCreateSchema = {
    properties: {
        username: {
            type: 'string',
            maxLength: 255,
            title: 'Username'
        },
        password_type: {
            type: 'string',
            maxLength: 255,
            title: 'Password Type'
        },
        member: {
            type: 'string',
            maxLength: 255,
            title: 'Member'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    required: ['username', 'password_type', 'member'],
    title: 'TacacsUserCreate'
} as const;

export const TacacsUserPublicSchema = {
    properties: {
        username: {
            type: 'string',
            maxLength: 255,
            title: 'Username'
        },
        password_type: {
            type: 'string',
            maxLength: 255,
            title: 'Password Type'
        },
        member: {
            type: 'string',
            maxLength: 255,
            title: 'Member'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        password: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['username', 'password_type', 'member', 'id', 'created_at'],
    title: 'TacacsUserPublic'
} as const;

export const TacacsUserUpdateSchema = {
    properties: {
        username: {
            type: 'string',
            maxLength: 255,
            title: 'Username'
        },
        password_type: {
            type: 'string',
            maxLength: 255,
            title: 'Password Type'
        },
        member: {
            type: 'string',
            maxLength: 255,
            title: 'Member'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    required: ['username', 'password_type', 'member'],
    title: 'TacacsUserUpdate'
} as const;

export const TacacsUsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/TacacsUserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'TacacsUsersPublic'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id', 'created_at'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 40,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;