// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type HostCreate = {
    name: string;
    ipv4_address?: (string | null);
    ipv6_address?: (string | null);
    secret_key: string;
    welcome_banner?: (string | null);
    reject_banner?: (string | null);
    motd_banner?: (string | null);
    failed_authentication_banner?: (string | null);
    parent?: (string | null);
    description?: (string | null);
};

export type HostPublic = {
    name: string;
    ipv4_address?: (string | null);
    ipv6_address?: (string | null);
    secret_key: string;
    welcome_banner?: (string | null);
    reject_banner?: (string | null);
    motd_banner?: (string | null);
    failed_authentication_banner?: (string | null);
    parent?: (string | null);
    description?: (string | null);
    id: string;
    created_at: string;
};

export type HostsPublic = {
    data: Array<HostPublic>;
    count: number;
};

export type HostUpdate = {
    name: string;
    ipv4_address?: (string | null);
    ipv6_address?: (string | null);
    secret_key: string;
    welcome_banner?: (string | null);
    reject_banner?: (string | null);
    motd_banner?: (string | null);
    failed_authentication_banner?: (string | null);
    parent?: (string | null);
    description?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at: string;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type MavisPublic = {
    ldap_server_type?: string;
    ldap_hosts?: string;
    ldap_base?: string;
    ldap_user?: string;
    ldap_passwd?: string;
    ldap_filter?: string;
    ldap_timeout?: number;
    require_tacacs_group_prefix?: number;
    tacacs_group_prefix?: string;
    id: string;
    created_at: string;
};

export type MavisUpdate = {
    ldap_server_type?: string;
    ldap_hosts?: string;
    ldap_base?: string;
    ldap_user?: string;
    ldap_passwd?: string;
    ldap_filter?: string;
    ldap_timeout?: number;
    require_tacacs_group_prefix?: number;
    tacacs_group_prefix?: string;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type ProfileCreate = {
    name: string;
    action: string;
    description?: (string | null);
};

export type ProfilePublic = {
    name: string;
    action: string;
    description?: (string | null);
    id: string;
    created_at: string;
};

export type ProfileScriptCreate = {
    condition: string;
    key: string;
    value: string;
    action: string;
    description?: (string | null);
    profile_id?: (string | null);
};

export type ProfileScriptPublic = {
    condition: string;
    key: string;
    value: string;
    action: string;
    description?: (string | null);
    profile_id: string;
    id: string;
    profile_name?: (string | null);
    created_at: string;
};

export type ProfileScriptSetCreate = {
    key: string;
    value: string;
    description?: (string | null);
    profilescript_id: string;
};

export type ProfileScriptSetPublic = {
    key: string;
    value: string;
    description?: (string | null);
    profilescript_id: string;
    id: string;
    profile_id?: (string | null);
    profile_name?: (string | null);
    profilescript_block?: (string | null);
    created_at: string;
};

export type ProfileScriptSetsPublic = {
    data: Array<ProfileScriptSetPublic>;
    count: number;
};

export type ProfileScriptSetUpdate = {
    key: string;
    value: string;
    description?: (string | null);
    profilescript_id: string;
};

export type ProfileScriptsPublic = {
    data: Array<ProfileScriptPublic>;
    count: number;
};

export type ProfileScriptUpdate = {
    condition: string;
    key: string;
    value: string;
    action: string;
    description?: (string | null);
    profile_id?: (string | null);
};

export type ProfilesPublic = {
    data: Array<ProfilePublic>;
    count: number;
};

export type ProfileUpdate = {
    name: string;
    action: string;
    description?: (string | null);
};

export type RulesetCreate = {
    name: string;
    enabled?: string;
    action: string;
    description?: (string | null);
};

export type RulesetPublic = {
    name: string;
    enabled?: string;
    action: string;
    description?: (string | null);
    id: string;
    created_at: string;
};

export type RulesetScriptCreate = {
    condition: string;
    key: string;
    value: string;
    action: string;
    description?: (string | null);
    ruleset_id: string;
};

export type RulesetScriptPublic = {
    condition: string;
    key: string;
    value: string;
    action: string;
    description?: (string | null);
    ruleset_id: string;
    id: string;
    ruleset_name?: (string | null);
    created_at: string;
};

export type RulesetScriptSetCreate = {
    key: string;
    value: string;
    description?: (string | null);
    rulesetscript_id: string;
};

export type RulesetScriptSetPublic = {
    key: string;
    value: string;
    description?: (string | null);
    rulesetscript_id: string;
    id: string;
    ruleset_id?: (string | null);
    ruleset_name?: (string | null);
    rulesetscript_block?: (string | null);
    created_at: string;
};

export type RulesetScriptSetsPublic = {
    data: Array<RulesetScriptSetPublic>;
    count: number;
};

export type RulesetScriptSetUpdate = {
    key: string;
    value: string;
    description?: (string | null);
    rulesetscript_id: string;
};

export type RulesetScriptsPublic = {
    data: Array<RulesetScriptPublic>;
    count: number;
};

export type RulesetScriptUpdate = {
    condition: string;
    key: string;
    value: string;
    action: string;
    description?: (string | null);
    ruleset_id: string;
};

export type RulesetsPublic = {
    data: Array<RulesetPublic>;
    count: number;
};

export type RulesetUpdate = {
    name: string;
    enabled?: string;
    action: string;
    description?: (string | null);
};

export type TacacsConfigCreate = {
    filename: string;
    description?: (string | null);
};

export type TacacsConfigPreviewPublic = {
    created_at: string;
    data?: (string | null);
};

export type TacacsConfigPublic = {
    filename: string;
    description?: (string | null);
    id: string;
    active: boolean;
    created_at: string;
    data?: (string | null);
};

export type TacacsConfigsPublic = {
    data: Array<TacacsConfigPublic>;
    count: number;
};

export type TacacsConfigUpdate = {
    filename: string;
    description?: (string | null);
};

export type TacacsGroupCreate = {
    group_name: string;
    description?: (string | null);
};

export type TacacsGroupPublic = {
    group_name: string;
    description?: (string | null);
    id: string;
    created_at: string;
};

export type TacacsGroupsPublic = {
    data: Array<TacacsGroupPublic>;
    count: number;
};

export type TacacsGroupUpdate = {
    group_name: string;
    description?: (string | null);
};

export type TacacsLogPublic = {
    filename: string;
    filepath: string;
    created_at?: string;
    id: string;
    data?: (string | null);
};

export type TacacsLogsPublic = {
    data: Array<TacacsLogPublic>;
    count: number;
};

export type TacacsNgSettingPublic = {
    ipv4_enabled?: boolean;
    ipv4_address?: string;
    ipv4_port?: number;
    ipv6_enabled?: boolean;
    ipv6_address?: string;
    ipv6_port?: number;
    instances_min?: number;
    instances_max?: number;
    background?: string;
    access_logfile_destination?: string;
    accounting_logfile_destination?: string;
    authentication_logfile_destination?: string;
    login_backend?: string;
    user_backend?: string;
    pap_backend?: string;
    id: string;
    created_at: string;
};

export type TacacsNgSettingUpdate = {
    ipv4_enabled?: boolean;
    ipv4_address?: string;
    ipv4_port?: number;
    ipv6_enabled?: boolean;
    ipv6_address?: string;
    ipv6_port?: number;
    instances_min?: number;
    instances_max?: number;
    background?: string;
    access_logfile_destination?: string;
    accounting_logfile_destination?: string;
    authentication_logfile_destination?: string;
    login_backend?: string;
    user_backend?: string;
    pap_backend?: string;
};

export type TacacsServiceCreate = {
    name: string;
    description?: (string | null);
};

export type TacacsServicePublic = {
    name: string;
    description?: (string | null);
    id: string;
    created_at: string;
};

export type TacacsServicesPublic = {
    data: Array<TacacsServicePublic>;
    count: number;
};

export type TacacsServiceUpdate = {
    name: string;
    description?: (string | null);
};

export type TacacsUserCreate = {
    username: string;
    password_type: string;
    member: string;
    description?: (string | null);
    password?: (string | null);
};

export type TacacsUserPublic = {
    username: string;
    password_type: string;
    member: string;
    description?: (string | null);
    password?: (string | null);
    id: string;
    created_at: string;
};

export type TacacsUsersPublic = {
    data: Array<TacacsUserPublic>;
    count: number;
};

export type TacacsUserUpdate = {
    username: string;
    password_type: string;
    member: string;
    description?: (string | null);
    password?: (string | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type HostsReadHostsData = {
    limit?: number;
    skip?: number;
};

export type HostsReadHostsResponse = (HostsPublic);

export type HostsCreateHostData = {
    requestBody: HostCreate;
};

export type HostsCreateHostResponse = (HostPublic);

export type HostsReadHostByIdData = {
    id: string;
};

export type HostsReadHostByIdResponse = (HostPublic);

export type HostsUpdateHostData = {
    id: string;
    requestBody: HostUpdate;
};

export type HostsUpdateHostResponse = (HostPublic);

export type HostsDeleteHostData = {
    id: string;
};

export type HostsDeleteHostResponse = (Message);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type MavisReadMavisSettingsResponse = (MavisPublic);

export type MavisUpdateMavisSettingsData = {
    requestBody: MavisUpdate;
};

export type MavisUpdateMavisSettingsResponse = (MavisPublic);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ProfilesReadProfilesData = {
    limit?: number;
    skip?: number;
};

export type ProfilesReadProfilesResponse = (ProfilesPublic);

export type ProfilesCreateProfileData = {
    requestBody: ProfileCreate;
};

export type ProfilesCreateProfileResponse = (ProfilePublic);

export type ProfilesPreviewProfilesResponse = (unknown);

export type ProfilesReadProfileByIdData = {
    id: string;
};

export type ProfilesReadProfileByIdResponse = (ProfilePublic);

export type ProfilesUpdateProfileData = {
    id: string;
    requestBody: ProfileUpdate;
};

export type ProfilesUpdateProfileResponse = (ProfilePublic);

export type ProfilesDeleteProfileData = {
    id: string;
};

export type ProfilesDeleteProfileResponse = (Message);

export type ProfilescriptsReadProfilescriptsData = {
    limit?: number;
    skip?: number;
};

export type ProfilescriptsReadProfilescriptsResponse = (ProfileScriptsPublic);

export type ProfilescriptsCreateProfilescriptData = {
    requestBody: ProfileScriptCreate;
};

export type ProfilescriptsCreateProfilescriptResponse = (ProfileScriptPublic);

export type ProfilescriptsReadProfilescriptByIdData = {
    id: string;
};

export type ProfilescriptsReadProfilescriptByIdResponse = (ProfileScriptPublic);

export type ProfilescriptsUpdateProfilescriptData = {
    id: string;
    requestBody: ProfileScriptUpdate;
};

export type ProfilescriptsUpdateProfilescriptResponse = (ProfileScriptPublic);

export type ProfilescriptsDeleteProfilescriptData = {
    id: string;
};

export type ProfilescriptsDeleteProfilescriptResponse = (Message);

export type ProfilescriptsetsReadProfilescriptsetsData = {
    limit?: number;
    skip?: number;
};

export type ProfilescriptsetsReadProfilescriptsetsResponse = (ProfileScriptSetsPublic);

export type ProfilescriptsetsCreateProfilescriptsetData = {
    requestBody: ProfileScriptSetCreate;
};

export type ProfilescriptsetsCreateProfilescriptsetResponse = (ProfileScriptSetPublic);

export type ProfilescriptsetsReadProfilescriptsetByIdData = {
    id: string;
};

export type ProfilescriptsetsReadProfilescriptsetByIdResponse = (ProfileScriptSetPublic);

export type ProfilescriptsetsUpdateProfilescriptsetData = {
    id: string;
    requestBody: ProfileScriptSetUpdate;
};

export type ProfilescriptsetsUpdateProfilescriptsetResponse = (ProfileScriptSetPublic);

export type ProfilescriptsetsDeleteProfilescriptsetData = {
    id: string;
};

export type ProfilescriptsetsDeleteProfilescriptsetResponse = (Message);

export type RulesetsReadRulesetsData = {
    limit?: number;
    skip?: number;
};

export type RulesetsReadRulesetsResponse = (RulesetsPublic);

export type RulesetsCreateRulesetData = {
    requestBody: RulesetCreate;
};

export type RulesetsCreateRulesetResponse = (RulesetPublic);

export type RulesetsPreviewRulesetsResponse = (unknown);

export type RulesetsReadRulesetByIdData = {
    id: string;
};

export type RulesetsReadRulesetByIdResponse = (RulesetPublic);

export type RulesetsUpdateRulesetData = {
    id: string;
    requestBody: RulesetUpdate;
};

export type RulesetsUpdateRulesetResponse = (RulesetPublic);

export type RulesetsDeleteRulesetData = {
    id: string;
};

export type RulesetsDeleteRulesetResponse = (Message);

export type RulesetscriptsReadRulesetscriptsData = {
    limit?: number;
    skip?: number;
};

export type RulesetscriptsReadRulesetscriptsResponse = (RulesetScriptsPublic);

export type RulesetscriptsCreateRulesetscriptData = {
    requestBody: RulesetScriptCreate;
};

export type RulesetscriptsCreateRulesetscriptResponse = (RulesetScriptPublic);

export type RulesetscriptsReadRulesetscriptByIdData = {
    id: string;
};

export type RulesetscriptsReadRulesetscriptByIdResponse = (RulesetScriptPublic);

export type RulesetscriptsUpdateRulesetscriptData = {
    id: string;
    requestBody: RulesetScriptUpdate;
};

export type RulesetscriptsUpdateRulesetscriptResponse = (RulesetScriptPublic);

export type RulesetscriptsDeleteRulesetscriptData = {
    id: string;
};

export type RulesetscriptsDeleteRulesetscriptResponse = (Message);

export type RulesetscriptsetsReadRulesetscriptsetsData = {
    limit?: number;
    skip?: number;
};

export type RulesetscriptsetsReadRulesetscriptsetsResponse = (RulesetScriptSetsPublic);

export type RulesetscriptsetsCreateRulesetscriptsetData = {
    requestBody: RulesetScriptSetCreate;
};

export type RulesetscriptsetsCreateRulesetscriptsetResponse = (RulesetScriptSetPublic);

export type RulesetscriptsetsReadRulesetscriptsetByIdData = {
    id: string;
};

export type RulesetscriptsetsReadRulesetscriptsetByIdResponse = (RulesetScriptSetPublic);

export type RulesetscriptsetsUpdateRulesetscriptsetData = {
    id: string;
    requestBody: RulesetScriptSetUpdate;
};

export type RulesetscriptsetsUpdateRulesetscriptsetResponse = (RulesetScriptSetPublic);

export type RulesetscriptsetsDeleteRulesetscriptsetData = {
    id: string;
};

export type RulesetscriptsetsDeleteRulesetscriptsetResponse = (Message);

export type TacacsConfigsReadTacacsConfigsData = {
    limit?: number;
    skip?: number;
    sortBy?: string;
    sortOrder?: string;
};

export type TacacsConfigsReadTacacsConfigsResponse = (TacacsConfigsPublic);

export type TacacsConfigsCreateTacacsConfigData = {
    requestBody: TacacsConfigCreate;
};

export type TacacsConfigsCreateTacacsConfigResponse = (TacacsConfigPublic);

export type TacacsConfigsGeneratePreviewTacacsConfigResponse = (TacacsConfigPreviewPublic);

export type TacacsConfigsGetActiveTacacsConfigResponse = (TacacsConfigPublic);

export type TacacsConfigsReadTacacsConfigByIdData = {
    id: string;
};

export type TacacsConfigsReadTacacsConfigByIdResponse = (TacacsConfigPublic);

export type TacacsConfigsUpdateTacacsConfigData = {
    id: string;
    requestBody: TacacsConfigUpdate;
};

export type TacacsConfigsUpdateTacacsConfigResponse = (TacacsConfigPublic);

export type TacacsConfigsDeleteTacacsConfigData = {
    id: string;
};

export type TacacsConfigsDeleteTacacsConfigResponse = (Message);

export type TacacsConfigsCheckTacacsConfigByIdData = {
    id: string;
};

export type TacacsConfigsCheckTacacsConfigByIdResponse = (unknown);

export type TacacsGroupsReadTacacsGroupsData = {
    limit?: number;
    skip?: number;
};

export type TacacsGroupsReadTacacsGroupsResponse = (TacacsGroupsPublic);

export type TacacsGroupsCreateTacacsGroupData = {
    requestBody: TacacsGroupCreate;
};

export type TacacsGroupsCreateTacacsGroupResponse = (TacacsGroupPublic);

export type TacacsGroupsReadTacacsGroupByIdData = {
    id: string;
};

export type TacacsGroupsReadTacacsGroupByIdResponse = (TacacsGroupPublic);

export type TacacsGroupsUpdateTacacsGroupData = {
    id: string;
    requestBody: TacacsGroupUpdate;
};

export type TacacsGroupsUpdateTacacsGroupResponse = (TacacsGroupPublic);

export type TacacsGroupsDeleteTacacsGroupData = {
    id: string;
};

export type TacacsGroupsDeleteTacacsGroupResponse = (Message);

export type TacacsLogsListLogFilesData = {
    limit?: number;
    search?: (string | null);
    skip?: number;
    sortBy?: string;
    sortOrder?: string;
};

export type TacacsLogsListLogFilesResponse = (TacacsLogsPublic);

export type TacacsLogsReadLogFileData = {
    id: string;
};

export type TacacsLogsReadLogFileResponse = (TacacsLogPublic);

export type TacacsNgSettingsReadTacacsNgSettingsResponse = (TacacsNgSettingPublic);

export type TacacsNgSettingsUpdateTacacsNgSettingsData = {
    requestBody: TacacsNgSettingUpdate;
};

export type TacacsNgSettingsUpdateTacacsNgSettingsResponse = (TacacsNgSettingPublic);

export type TacacsServicesReadTacacsServicesData = {
    limit?: number;
    skip?: number;
};

export type TacacsServicesReadTacacsServicesResponse = (TacacsServicesPublic);

export type TacacsServicesCreateTacacsServiceData = {
    requestBody: TacacsServiceCreate;
};

export type TacacsServicesCreateTacacsServiceResponse = (TacacsServicePublic);

export type TacacsServicesReadTacacsServiceByIdData = {
    id: string;
};

export type TacacsServicesReadTacacsServiceByIdResponse = (TacacsServicePublic);

export type TacacsServicesUpdateTacacsServiceData = {
    id: string;
    requestBody: TacacsServiceUpdate;
};

export type TacacsServicesUpdateTacacsServiceResponse = (TacacsServicePublic);

export type TacacsServicesDeleteTacacsServiceData = {
    id: string;
};

export type TacacsServicesDeleteTacacsServiceResponse = (Message);

export type TacacsUsersReadTacacsUsersData = {
    limit?: number;
    skip?: number;
};

export type TacacsUsersReadTacacsUsersResponse = (TacacsUsersPublic);

export type TacacsUsersCreateTacacsUserData = {
    requestBody: TacacsUserCreate;
};

export type TacacsUsersCreateTacacsUserResponse = (TacacsUserPublic);

export type TacacsUsersReadTacacsUserByIdData = {
    id: string;
};

export type TacacsUsersReadTacacsUserByIdResponse = (TacacsUserPublic);

export type TacacsUsersUpdateTacacsUserData = {
    id: string;
    requestBody: TacacsUserUpdate;
};

export type TacacsUsersUpdateTacacsUserResponse = (TacacsUserPublic);

export type TacacsUsersDeleteTacacsUserData = {
    id: string;
};

export type TacacsUsersDeleteTacacsUserResponse = (Message);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);