// This file is auto-generated by @hey-api/openapi-ts

export type AaaStatisticsDateRangePublic = {
    authentication_failed_count_by_user?: Array<{
        [key: string]: unknown;
    }>;
    authentication_success_count_by_user?: Array<{
        [key: string]: unknown;
    }>;
    authorization_deny_count_by_user?: Array<{
        [key: string]: unknown;
    }>;
    authentication_success_count_by_user_source_ip?: Array<{
        [key: string]: unknown;
    }>;
    authentication_success_count_by_nas_ip?: Array<{
        [key: string]: unknown;
    }>;
    last_range_days_authentication_success?: Array<{
        [key: string]: unknown;
    }>;
    last_range_days_authentication_fail?: Array<{
        [key: string]: unknown;
    }>;
    last_range_days_authorization_permit?: Array<{
        [key: string]: unknown;
    }>;
    last_range_days_authorization_deny?: Array<{
        [key: string]: unknown;
    }>;
    last_range_days_accounting_start?: Array<{
        [key: string]: unknown;
    }>;
    last_range_days_accounting_stop?: Array<{
        [key: string]: unknown;
    }>;
};

export type AaaStatisticsTodayPublic = {
    authentication_failed_count_by_user?: Array<{
        [key: string]: unknown;
    }>;
    authentication_success_count_by_user?: Array<{
        [key: string]: unknown;
    }>;
    authorization_deny_count_by_user?: Array<{
        [key: string]: unknown;
    }>;
    authentication_success_count_by_user_source_ip?: Array<{
        [key: string]: unknown;
    }>;
    last_7_days_authentication_success?: Array<{
        [key: string]: unknown;
    }>;
    last_7_days_authentication_fail?: Array<{
        [key: string]: unknown;
    }>;
    last_7_days_authorization_permit?: Array<{
        [key: string]: unknown;
    }>;
    last_7_days_authorization_deny?: Array<{
        [key: string]: unknown;
    }>;
    last_7_days_accounting_start?: Array<{
        [key: string]: unknown;
    }>;
    last_7_days_accounting_stop?: Array<{
        [key: string]: unknown;
    }>;
    today?: (string | null);
    today_total_authentication_events?: number;
    today_list_authentication_details?: Array<{
        [key: string]: unknown;
    }>;
    today_unique_user_nas_client_combinations?: number;
    today_successful_logins?: number;
    today_failed_logins?: number;
    today_unique_user_source_ip_count?: number;
    today_unique_nas_ip_count?: number;
    today_authentication_failed_count_by_user?: Array<{
        [key: string]: unknown;
    }>;
    today_authentication_success_count_by_user?: Array<{
        [key: string]: unknown;
    }>;
    today_authentication_success_count_by_user_source_ip?: Array<{
        [key: string]: unknown;
    }>;
    today_authentication_success_count_by_nas_ip?: Array<{
        [key: string]: unknown;
    }>;
};

export type AccountingStatisticPublic = {
    username: string;
    nas_ip: string;
    user_source_ip: string;
    start_count?: number;
    stop_count?: number;
    log_date?: string;
    id: string;
    updated_at: string;
};

export type AccountingStatisticsPublic = {
    data: Array<AccountingStatisticPublic>;
    count: number;
};

export type AlertEventPublic = {
    triggered_at?: string;
    payload_snapshot?: (string | null);
    status?: string;
    error_message?: (string | null);
    id: string;
    rule_id: string;
    channel_id: string;
    rule_name?: (string | null);
    channel_name?: (string | null);
    rule_severity?: (string | null);
    created_at: string;
};

export type AlertEventsPublic = {
    data: Array<AlertEventPublic>;
    count: number;
};

export type AlertRuleCreate = {
    name: string;
    description?: (string | null);
    enabled?: boolean;
    log_type: string;
    condition_field: string;
    condition_operator: string;
    threshold?: (number | null);
    time_window_minutes?: number;
    severity?: string;
    cooldown_minutes?: number;
    is_system?: boolean;
};

export type AlertRulePublic = {
    name: string;
    description?: (string | null);
    enabled?: boolean;
    log_type: string;
    condition_field: string;
    condition_operator: string;
    threshold?: (number | null);
    time_window_minutes?: number;
    severity?: string;
    cooldown_minutes?: number;
    is_system?: boolean;
    id: string;
    last_fired_at: (string | null);
    created_at: string;
    updated_at: string;
};

export type AlertRulesPublic = {
    data: Array<AlertRulePublic>;
    count: number;
};

export type AlertRuleUpdate = {
    name?: (string | null);
    description?: (string | null);
    enabled?: (boolean | null);
    log_type?: (string | null);
    condition_field?: (string | null);
    condition_operator?: (string | null);
    threshold?: (number | null);
    time_window_minutes?: (number | null);
    severity?: (string | null);
    cooldown_minutes?: (number | null);
};

export type AlertStatistics = {
    total: number;
    sent: number;
    failed: number;
    by_severity: Array<AlertStatisticsSeverityItem>;
    by_rule: Array<AlertStatisticsRuleItem>;
    last_24h: number;
    last_7d: number;
};

export type AlertStatisticsRuleItem = {
    rule_name: string;
    count: number;
};

export type AlertStatisticsSeverityItem = {
    severity: string;
    count: number;
};

export type AnomalyDetectionResultPublic = {
    subject_type: string;
    subject_value: string;
    scored_at?: string;
    anomaly_score: number;
    is_anomaly?: boolean;
    risk_level?: string;
    feature_snapshot?: (string | null);
    id: string;
    created_at: string;
    updated_at: string;
};

export type AnomalyDetectionResultsPublic = {
    data: Array<AnomalyDetectionResultPublic>;
    count: number;
};

export type AuditLogPublic = {
    action: string;
    entity_type: string;
    entity_id?: (string | null);
    description?: (string | null);
    user_agent?: (string | null);
    old_values?: (string | null);
    new_values?: (string | null);
    id: string;
    user_id: (string | null);
    user_email: string;
    ip_address: (string | null);
    created_at: string;
};

export type AuditLogsPublic = {
    data: Array<AuditLogPublic>;
    count: number;
};

export type AuthenticationStatisticPublic = {
    username: string;
    nas_ip: string;
    user_source_ip: string;
    success_count?: number;
    fail_count?: number;
    log_date?: string;
    id: string;
    updated_at: string;
};

export type AuthenticationStatisticsPublic = {
    data: Array<AuthenticationStatisticPublic>;
    count: number;
};

export type AuthorizationStatisticPublic = {
    username: string;
    nas_ip: string;
    user_source_ip: string;
    permit_count?: number;
    deny_count?: number;
    log_date?: string;
    id: string;
    updated_at: string;
};

export type AuthorizationStatisticsPublic = {
    data: Array<AuthorizationStatisticPublic>;
    count: number;
};

export type AuthProviderConfigPublic = {
    provider: string;
    enabled: boolean;
    config: {
        [key: string]: unknown;
    };
    secret_is_set: boolean;
};

export type AuthProviderConfigUpdate = {
    enabled?: (boolean | null);
    config?: ({
    [key: string]: unknown;
} | null);
    secret?: (string | null);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type ConfigurationOptionCreate = {
    name: string;
    config_option: string;
    description?: (string | null);
};

export type ConfigurationOptionPublic = {
    name: string;
    config_option: string;
    description?: (string | null);
    id: string;
    created_at: string;
    updated_at: string;
};

export type ConfigurationOptionsPublic = {
    data: Array<ConfigurationOptionPublic>;
    count: number;
};

export type ConfigurationOptionUpdate = {
    name: string;
    config_option: string;
    description?: (string | null);
};

export type HostCreate = {
    name: string;
    ipv4_address?: (string | null);
    ipv6_address?: (string | null);
    secret_key: string;
    welcome_banner?: (string | null);
    reject_banner?: (string | null);
    motd_banner?: (string | null);
    failed_authentication_banner?: (string | null);
    parent?: (string | null);
    description?: (string | null);
};

export type HostPublic = {
    name: string;
    ipv4_address?: (string | null);
    ipv6_address?: (string | null);
    secret_key: string;
    welcome_banner?: (string | null);
    reject_banner?: (string | null);
    motd_banner?: (string | null);
    failed_authentication_banner?: (string | null);
    parent?: (string | null);
    description?: (string | null);
    id: string;
    created_at: string;
    updated_at: string;
};

export type HostsPublic = {
    data: Array<HostPublic>;
    count: number;
};

export type HostUpdate = {
    name: string;
    ipv4_address?: (string | null);
    ipv6_address?: (string | null);
    secret_key: string;
    welcome_banner?: (string | null);
    reject_banner?: (string | null);
    motd_banner?: (string | null);
    failed_authentication_banner?: (string | null);
    parent?: (string | null);
    description?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at: string;
    updated_at: string;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type MavisCreate = {
    mavis_key: string;
    mavis_value: string;
};

export type MavisesPublic = {
    data: Array<MavisPublic>;
    count: number;
};

export type MavisPreviewPublic = {
    data?: (string | null);
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type MavisPublic = {
    mavis_key: string;
    mavis_value: string;
    id: string;
    created_at: string;
    updated_at: string;
};

export type MavisUpdate = {
    mavis_key: string;
    mavis_value: string;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type NotificationChannelCreate = {
    name: string;
    channel_type: string;
    config_json?: string;
    enabled?: boolean;
};

export type NotificationChannelPublic = {
    name: string;
    channel_type: string;
    config_json?: string;
    enabled?: boolean;
    id: string;
    created_at: string;
    updated_at: string;
};

export type NotificationChannelsPublic = {
    data: Array<NotificationChannelPublic>;
    count: number;
};

export type NotificationChannelUpdate = {
    name?: (string | null);
    channel_type?: (string | null);
    config_json?: (string | null);
    enabled?: (boolean | null);
};

export type PasskeyAuthenticateCompleteRequest = {
    credential: {
        [key: string]: unknown;
    };
};

export type PasskeyRegisterCompleteRequest = {
    credential: {
        [key: string]: unknown;
    };
    name?: (string | null);
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type ProfileCreate = {
    name: string;
    action: string;
    description?: (string | null);
};

export type ProfilePreviewPublic = {
    data?: (string | null);
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type ProfilePublic = {
    name: string;
    action: string;
    description?: (string | null);
    id: string;
    created_at: string;
    updated_at: string;
};

export type ProfileScriptCreate = {
    condition: string;
    key: string;
    value: string;
    action: string;
    description?: (string | null);
    profile_id?: (string | null);
};

export type ProfileScriptPublic = {
    condition: string;
    key: string;
    value: string;
    action: string;
    description?: (string | null);
    profile_id: string;
    id: string;
    profile_name?: (string | null);
    created_at: string;
    updated_at: string;
};

export type ProfileScriptSetCreate = {
    key: string;
    value: string;
    description?: (string | null);
    profilescript_id: string;
};

export type ProfileScriptSetPublic = {
    key: string;
    value: string;
    description?: (string | null);
    profilescript_id: string;
    id: string;
    profile_id?: (string | null);
    profile_name?: (string | null);
    profilescript_block?: (string | null);
    created_at: string;
    updated_at: string;
};

export type ProfileScriptSetsPublic = {
    data: Array<ProfileScriptSetPublic>;
    count: number;
};

export type ProfileScriptSetUpdate = {
    key: string;
    value: string;
    description?: (string | null);
    profilescript_id: string;
};

export type ProfileScriptsPublic = {
    data: Array<ProfileScriptPublic>;
    count: number;
};

export type ProfileScriptUpdate = {
    condition: string;
    key: string;
    value: string;
    action: string;
    description?: (string | null);
    profile_id?: (string | null);
};

export type ProfilesPublic = {
    data: Array<ProfilePublic>;
    count: number;
};

export type ProfileUpdate = {
    name: string;
    action: string;
    description?: (string | null);
};

export type RulesetCreate = {
    name: string;
    enabled?: string;
    action: string;
    description?: (string | null);
};

export type RulesetPreviewPublic = {
    data?: (string | null);
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type RulesetPublic = {
    name: string;
    enabled?: string;
    action: string;
    description?: (string | null);
    id: string;
    created_at: string;
    updated_at: string;
};

export type RulesetScriptCreate = {
    condition: string;
    key: string;
    value: string;
    action: string;
    description?: (string | null);
    ruleset_id: string;
};

export type RulesetScriptPublic = {
    condition: string;
    key: string;
    value: string;
    action: string;
    description?: (string | null);
    ruleset_id: string;
    id: string;
    ruleset_name?: (string | null);
    created_at: string;
    updated_at: string;
};

export type RulesetScriptSetCreate = {
    key: string;
    value: string;
    description?: (string | null);
    rulesetscript_id: string;
};

export type RulesetScriptSetPublic = {
    key: string;
    value: string;
    description?: (string | null);
    rulesetscript_id: string;
    id: string;
    ruleset_id?: (string | null);
    ruleset_name?: (string | null);
    rulesetscript_block?: (string | null);
    created_at: string;
    updated_at: string;
};

export type RulesetScriptSetsPublic = {
    data: Array<RulesetScriptSetPublic>;
    count: number;
};

export type RulesetScriptSetUpdate = {
    key: string;
    value: string;
    description?: (string | null);
    rulesetscript_id: string;
};

export type RulesetScriptsPublic = {
    data: Array<RulesetScriptPublic>;
    count: number;
};

export type RulesetScriptUpdate = {
    condition: string;
    key: string;
    value: string;
    action: string;
    description?: (string | null);
    ruleset_id: string;
};

export type RulesetsPublic = {
    data: Array<RulesetPublic>;
    count: number;
};

export type RulesetUpdate = {
    name: string;
    enabled?: string;
    action: string;
    description?: (string | null);
};

export type TacacsConfigCreate = {
    filename: string;
    description?: (string | null);
};

export type TacacsConfigPreviewPublic = {
    created_at: string;
    data?: (string | null);
    updated_at: string;
};

export type TacacsConfigPublic = {
    filename: string;
    description?: (string | null);
    id: string;
    active: boolean;
    created_at: string;
    updated_at: string;
    data?: (string | null);
};

export type TacacsConfigsPublic = {
    data: Array<TacacsConfigPublic>;
    count: number;
};

export type TacacsConfigUpdate = {
    filename: string;
    description?: (string | null);
};

export type TacacsGroupCreate = {
    group_name: string;
    description?: (string | null);
};

export type TacacsGroupPublic = {
    group_name: string;
    description?: (string | null);
    id: string;
    created_at: string;
    updated_at: string;
};

export type TacacsGroupsPublic = {
    data: Array<TacacsGroupPublic>;
    count: number;
};

export type TacacsGroupUpdate = {
    group_name: string;
    description?: (string | null);
};

export type TacacsLogDailySummary = {
    date: string;
    authentication: TacacsLogTypeSummary;
    authorization: TacacsLogTypeSummary;
    accounting: TacacsLogTypeSummary;
};

export type TacacsLogEvent = {
    timestamp: string;
    log_type: string;
    username: string;
    nas_ip: string;
    client_ip: string;
    result: string;
    message: string;
    command?: (string | null);
    port?: (string | null);
    session_id?: (string | null);
};

export type TacacsLogEventsPublic = {
    data: Array<TacacsLogEvent>;
    count: number;
};

export type TacacsLogLatestDate = {
    date: string;
};

export type TacacsLogPublic = {
    filename: string;
    filepath: string;
    created_at?: string;
    id: string;
    updated_at: string;
    data?: (string | null);
};

export type TacacsLogsPublic = {
    data: Array<TacacsLogPublic>;
    count: number;
};

export type TacacsLogTypeSummary = {
    success?: number;
    failed?: number;
    permit?: number;
    deny?: number;
    start?: number;
    stop?: number;
    total?: number;
};

export type TacacsNgSettingPublic = {
    ipv4_enabled?: boolean;
    ipv4_address?: string;
    ipv4_port?: number;
    ipv6_enabled?: boolean;
    ipv6_address?: string;
    ipv6_port?: number;
    instances_min?: number;
    instances_max?: number;
    background?: string;
    access_logfile_destination?: string;
    authentication_logfile_destination?: string;
    authorization_logfile_destination?: string;
    accounting_logfile_destination?: string;
    login_backend?: string;
    user_backend?: string;
    pap_backend?: string;
    timezone?: string;
    id: string;
    created_at: string;
    updated_at: string;
};

export type TacacsNgSettingUpdate = {
    ipv4_enabled?: boolean;
    ipv4_address?: string;
    ipv4_port?: number;
    ipv6_enabled?: boolean;
    ipv6_address?: string;
    ipv6_port?: number;
    instances_min?: number;
    instances_max?: number;
    background?: string;
    access_logfile_destination?: string;
    authentication_logfile_destination?: string;
    authorization_logfile_destination?: string;
    accounting_logfile_destination?: string;
    login_backend?: string;
    user_backend?: string;
    pap_backend?: string;
    timezone?: string;
};

export type TacacsServiceCreate = {
    name: string;
    description?: (string | null);
};

export type TacacsServicePublic = {
    name: string;
    description?: (string | null);
    id: string;
    created_at: string;
    updated_at: string;
};

export type TacacsServicesPublic = {
    data: Array<TacacsServicePublic>;
    count: number;
};

export type TacacsServiceUpdate = {
    name: string;
    description?: (string | null);
};

export type TacacsUserCreate = {
    username: string;
    password_type: string;
    member: string;
    description?: (string | null);
    password?: (string | null);
};

export type TacacsUserPublic = {
    id: string;
    username: string;
    password_type: string;
    member: string;
    description?: (string | null);
    created_at: string;
    updated_at: string;
};

export type TacacsUsersPublic = {
    data: Array<TacacsUserPublic>;
    count: number;
};

export type TacacsUserUpdate = {
    username?: (string | null);
    password_type?: (string | null);
    member?: (string | null);
    description?: (string | null);
    password?: (string | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
    password_login_disabled?: boolean;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at: string;
    updated_at: string;
    password_login_disabled: boolean;
    login_methods?: Array<(string)>;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
    password_login_disabled?: (boolean | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    password_login_disabled?: (boolean | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type WebAuthnCredentialPublic = {
    id: string;
    credential_id: string;
    name: (string | null);
    created_at: string;
    last_used_at: (string | null);
};

export type WebAuthnCredentialsPublic = {
    data: Array<WebAuthnCredentialPublic>;
    count: number;
};

export type AaaStatisticsReadAaaStatisticsData = {
    limit?: number;
    skip?: number;
};

export type AaaStatisticsReadAaaStatisticsResponse = (AaaStatisticsTodayPublic);

export type AaaStatisticsReadAaaStatisticsRangeData = {
    limit?: number;
    rangeDate?: (string | null);
    skip?: number;
};

export type AaaStatisticsReadAaaStatisticsRangeResponse = (AaaStatisticsDateRangePublic);

export type AaaStatisticsRunAaaStatisticsData = {
    date?: (string | null);
};

export type AaaStatisticsRunAaaStatisticsResponse = (unknown);

export type AccountingStatisticsReadAccountingStatisticsData = {
    dateFrom?: (string | null);
    dateTo?: (string | null);
    limit?: number;
    skip?: number;
    sortBy?: string;
    sortOrder?: string;
};

export type AccountingStatisticsReadAccountingStatisticsResponse = (AccountingStatisticsPublic);

export type AdminListAuthProvidersResponse = (Array<AuthProviderConfigPublic>);

export type AdminGetAuthProviderData = {
    provider: string;
};

export type AdminGetAuthProviderResponse = (AuthProviderConfigPublic);

export type AdminUpdateAuthProviderData = {
    provider: string;
    requestBody: AuthProviderConfigUpdate;
};

export type AdminUpdateAuthProviderResponse = (AuthProviderConfigPublic);

export type AlertEventsReadAlertStatisticsResponse = (AlertStatistics);

export type AlertEventsReadAlertEventsData = {
    limit?: number;
    ruleId?: (string | null);
    skip?: number;
    status?: (string | null);
};

export type AlertEventsReadAlertEventsResponse = (AlertEventsPublic);

export type AlertRulesReadAlertRulesData = {
    limit?: number;
    skip?: number;
};

export type AlertRulesReadAlertRulesResponse = (AlertRulesPublic);

export type AlertRulesCreateAlertRuleData = {
    requestBody: AlertRuleCreate;
};

export type AlertRulesCreateAlertRuleResponse = (AlertRulePublic);

export type AlertRulesReadAlertRuleByIdData = {
    id: string;
};

export type AlertRulesReadAlertRuleByIdResponse = (AlertRulePublic);

export type AlertRulesUpdateAlertRuleData = {
    id: string;
    requestBody: AlertRuleUpdate;
};

export type AlertRulesUpdateAlertRuleResponse = (AlertRulePublic);

export type AlertRulesDeleteAlertRuleData = {
    id: string;
};

export type AlertRulesDeleteAlertRuleResponse = ({
    [key: string]: (string);
});

export type AnomalyDetectionReadAnomalyResultsData = {
    isAnomalyOnly?: boolean;
    limit?: number;
    skip?: number;
    sortBy?: string;
    subjectType?: (string | null);
};

export type AnomalyDetectionReadAnomalyResultsResponse = (AnomalyDetectionResultsPublic);

export type AnomalyDetectionRetrainAnomalyModelResponse = ({
    [key: string]: unknown;
});

export type AuditLogsReadAuditLogsData = {
    limit?: number;
    search?: (string | null);
    skip?: number;
};

export type AuditLogsReadAuditLogsResponse = (AuditLogsPublic);

export type AuditLogsReadAuditLogByIdData = {
    id: string;
};

export type AuditLogsReadAuditLogByIdResponse = (AuditLogPublic);

export type AuditLogsPurgeAuditLogsResponse = ({
    [key: string]: (number);
});

export type AuthenticationStatisticsReadAuthenticationStatisticsData = {
    dateFrom?: (string | null);
    dateTo?: (string | null);
    limit?: number;
    skip?: number;
    sortBy?: string;
    sortOrder?: string;
};

export type AuthenticationStatisticsReadAuthenticationStatisticsResponse = (AuthenticationStatisticsPublic);

export type AuthorizationStatisticsReadAuthorizationStatisticsData = {
    dateFrom?: (string | null);
    dateTo?: (string | null);
    limit?: number;
    skip?: number;
    sortBy?: string;
    sortOrder?: string;
};

export type AuthorizationStatisticsReadAuthorizationStatisticsResponse = (AuthorizationStatisticsPublic);

export type AuthProvidersAuthProvidersStatusResponse = ({
    [key: string]: (boolean);
});

export type ConfigurationOptionsReadConfigurationOptionsData = {
    limit?: number;
    search?: (string | null);
    skip?: number;
};

export type ConfigurationOptionsReadConfigurationOptionsResponse = (ConfigurationOptionsPublic);

export type ConfigurationOptionsCreateConfigurationOptionData = {
    requestBody: ConfigurationOptionCreate;
};

export type ConfigurationOptionsCreateConfigurationOptionResponse = (ConfigurationOptionPublic);

export type ConfigurationOptionsReadConfigurationOptionByIdData = {
    id: string;
};

export type ConfigurationOptionsReadConfigurationOptionByIdResponse = (ConfigurationOptionPublic);

export type ConfigurationOptionsUpdateConfigurationOptionData = {
    id: string;
    requestBody: ConfigurationOptionUpdate;
};

export type ConfigurationOptionsUpdateConfigurationOptionResponse = (ConfigurationOptionPublic);

export type ConfigurationOptionsDeleteConfigurationOptionData = {
    id: string;
};

export type ConfigurationOptionsDeleteConfigurationOptionResponse = (Message);

export type HostsReadHostsData = {
    limit?: number;
    search?: (string | null);
    skip?: number;
};

export type HostsReadHostsResponse = (HostsPublic);

export type HostsCreateHostData = {
    requestBody: HostCreate;
};

export type HostsCreateHostResponse = (HostPublic);

export type HostsReadHostByIdData = {
    id: string;
};

export type HostsReadHostByIdResponse = (HostPublic);

export type HostsUpdateHostData = {
    id: string;
    requestBody: HostUpdate;
};

export type HostsUpdateHostResponse = (HostPublic);

export type HostsDeleteHostData = {
    id: string;
};

export type HostsDeleteHostResponse = (Message);

export type ItemsReadItemsData = {
    limit?: number;
    search?: (string | null);
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type MavisesReadMavisesData = {
    limit?: number;
    search?: (string | null);
    skip?: number;
};

export type MavisesReadMavisesResponse = (MavisesPublic);

export type MavisesCreateMavisData = {
    requestBody: MavisCreate;
};

export type MavisesCreateMavisResponse = (MavisPublic);

export type MavisesPreviewMavisResponse = (MavisPreviewPublic);

export type MavisesReadMavisByIdData = {
    id: string;
};

export type MavisesReadMavisByIdResponse = (MavisPublic);

export type MavisesUpdateMavisData = {
    id: string;
    requestBody: MavisUpdate;
};

export type MavisesUpdateMavisResponse = (MavisPublic);

export type MavisesDeleteMavisData = {
    id: string;
};

export type MavisesDeleteMavisResponse = (Message);

export type NotificationChannelsReadNotificationChannelsData = {
    limit?: number;
    skip?: number;
};

export type NotificationChannelsReadNotificationChannelsResponse = (NotificationChannelsPublic);

export type NotificationChannelsCreateNotificationChannelData = {
    requestBody: NotificationChannelCreate;
};

export type NotificationChannelsCreateNotificationChannelResponse = (NotificationChannelPublic);

export type NotificationChannelsReadNotificationChannelByIdData = {
    id: string;
};

export type NotificationChannelsReadNotificationChannelByIdResponse = (NotificationChannelPublic);

export type NotificationChannelsUpdateNotificationChannelData = {
    id: string;
    requestBody: NotificationChannelUpdate;
};

export type NotificationChannelsUpdateNotificationChannelResponse = (NotificationChannelPublic);

export type NotificationChannelsDeleteNotificationChannelData = {
    id: string;
};

export type NotificationChannelsDeleteNotificationChannelResponse = ({
    [key: string]: (string);
});

export type NotificationChannelsTestNotificationChannelData = {
    id: string;
};

export type NotificationChannelsTestNotificationChannelResponse = ({
    [key: string]: (string);
});

export type OauthGoogleAuthorizeResponse = ({
    [key: string]: (string);
});

export type OauthGoogleCallbackData = {
    code: string;
    state: string;
};

export type OauthGoogleCallbackResponse = (unknown);

export type OauthKeycloakAuthorizeResponse = ({
    [key: string]: (string);
});

export type OauthKeycloakCallbackData = {
    code: string;
    state: string;
};

export type OauthKeycloakCallbackResponse = (unknown);

export type PasskeysRegisterBeginResponse = (unknown);

export type PasskeysRegisterCompleteData = {
    requestBody: PasskeyRegisterCompleteRequest;
};

export type PasskeysRegisterCompleteResponse = (WebAuthnCredentialPublic);

export type PasskeysListCredentialsResponse = (WebAuthnCredentialsPublic);

export type PasskeysDeleteCredentialData = {
    credentialId: string;
};

export type PasskeysDeleteCredentialResponse = (Message);

export type PasskeysAuthenticateBeginResponse = (unknown);

export type PasskeysAuthenticateCompleteData = {
    requestBody: PasskeyAuthenticateCompleteRequest;
};

export type PasskeysAuthenticateCompleteResponse = (Token);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type ProfilesReadProfilesData = {
    limit?: number;
    search?: (string | null);
    skip?: number;
};

export type ProfilesReadProfilesResponse = (ProfilesPublic);

export type ProfilesCreateProfileData = {
    requestBody: ProfileCreate;
};

export type ProfilesCreateProfileResponse = (ProfilePublic);

export type ProfilesPreviewProfilesResponse = (ProfilePreviewPublic);

export type ProfilesReadProfileByIdData = {
    id: string;
};

export type ProfilesReadProfileByIdResponse = (ProfilePublic);

export type ProfilesUpdateProfileData = {
    id: string;
    requestBody: ProfileUpdate;
};

export type ProfilesUpdateProfileResponse = (ProfilePublic);

export type ProfilesDeleteProfileData = {
    id: string;
};

export type ProfilesDeleteProfileResponse = (Message);

export type ProfilescriptsReadProfilescriptsData = {
    limit?: number;
    search?: (string | null);
    skip?: number;
};

export type ProfilescriptsReadProfilescriptsResponse = (ProfileScriptsPublic);

export type ProfilescriptsCreateProfilescriptData = {
    requestBody: ProfileScriptCreate;
};

export type ProfilescriptsCreateProfilescriptResponse = (ProfileScriptPublic);

export type ProfilescriptsReadProfilescriptByIdData = {
    id: string;
};

export type ProfilescriptsReadProfilescriptByIdResponse = (ProfileScriptPublic);

export type ProfilescriptsUpdateProfilescriptData = {
    id: string;
    requestBody: ProfileScriptUpdate;
};

export type ProfilescriptsUpdateProfilescriptResponse = (ProfileScriptPublic);

export type ProfilescriptsDeleteProfilescriptData = {
    id: string;
};

export type ProfilescriptsDeleteProfilescriptResponse = (Message);

export type ProfilescriptsetsReadProfilescriptsetsData = {
    limit?: number;
    search?: (string | null);
    skip?: number;
};

export type ProfilescriptsetsReadProfilescriptsetsResponse = (ProfileScriptSetsPublic);

export type ProfilescriptsetsCreateProfilescriptsetData = {
    requestBody: ProfileScriptSetCreate;
};

export type ProfilescriptsetsCreateProfilescriptsetResponse = (ProfileScriptSetPublic);

export type ProfilescriptsetsReadProfilescriptsetByIdData = {
    id: string;
};

export type ProfilescriptsetsReadProfilescriptsetByIdResponse = (ProfileScriptSetPublic);

export type ProfilescriptsetsUpdateProfilescriptsetData = {
    id: string;
    requestBody: ProfileScriptSetUpdate;
};

export type ProfilescriptsetsUpdateProfilescriptsetResponse = (ProfileScriptSetPublic);

export type ProfilescriptsetsDeleteProfilescriptsetData = {
    id: string;
};

export type ProfilescriptsetsDeleteProfilescriptsetResponse = (Message);

export type RulesetsReadRulesetsData = {
    limit?: number;
    search?: (string | null);
    skip?: number;
};

export type RulesetsReadRulesetsResponse = (RulesetsPublic);

export type RulesetsCreateRulesetData = {
    requestBody: RulesetCreate;
};

export type RulesetsCreateRulesetResponse = (RulesetPublic);

export type RulesetsPreviewRulesetsResponse = (RulesetPreviewPublic);

export type RulesetsReadRulesetByIdData = {
    id: string;
};

export type RulesetsReadRulesetByIdResponse = (RulesetPublic);

export type RulesetsUpdateRulesetData = {
    id: string;
    requestBody: RulesetUpdate;
};

export type RulesetsUpdateRulesetResponse = (RulesetPublic);

export type RulesetsDeleteRulesetData = {
    id: string;
};

export type RulesetsDeleteRulesetResponse = (Message);

export type RulesetscriptsReadRulesetscriptsData = {
    limit?: number;
    search?: (string | null);
    skip?: number;
};

export type RulesetscriptsReadRulesetscriptsResponse = (RulesetScriptsPublic);

export type RulesetscriptsCreateRulesetscriptData = {
    requestBody: RulesetScriptCreate;
};

export type RulesetscriptsCreateRulesetscriptResponse = (RulesetScriptPublic);

export type RulesetscriptsReadRulesetscriptByIdData = {
    id: string;
};

export type RulesetscriptsReadRulesetscriptByIdResponse = (RulesetScriptPublic);

export type RulesetscriptsUpdateRulesetscriptData = {
    id: string;
    requestBody: RulesetScriptUpdate;
};

export type RulesetscriptsUpdateRulesetscriptResponse = (RulesetScriptPublic);

export type RulesetscriptsDeleteRulesetscriptData = {
    id: string;
};

export type RulesetscriptsDeleteRulesetscriptResponse = (Message);

export type RulesetscriptsetsReadRulesetscriptsetsData = {
    limit?: number;
    search?: (string | null);
    skip?: number;
};

export type RulesetscriptsetsReadRulesetscriptsetsResponse = (RulesetScriptSetsPublic);

export type RulesetscriptsetsCreateRulesetscriptsetData = {
    requestBody: RulesetScriptSetCreate;
};

export type RulesetscriptsetsCreateRulesetscriptsetResponse = (RulesetScriptSetPublic);

export type RulesetscriptsetsReadRulesetscriptsetByIdData = {
    id: string;
};

export type RulesetscriptsetsReadRulesetscriptsetByIdResponse = (RulesetScriptSetPublic);

export type RulesetscriptsetsUpdateRulesetscriptsetData = {
    id: string;
    requestBody: RulesetScriptSetUpdate;
};

export type RulesetscriptsetsUpdateRulesetscriptsetResponse = (RulesetScriptSetPublic);

export type RulesetscriptsetsDeleteRulesetscriptsetData = {
    id: string;
};

export type RulesetscriptsetsDeleteRulesetscriptsetResponse = (Message);

export type TacacsConfigsReadTacacsConfigsData = {
    limit?: number;
    search?: (string | null);
    skip?: number;
    sortBy?: string;
    sortOrder?: string;
};

export type TacacsConfigsReadTacacsConfigsResponse = (TacacsConfigsPublic);

export type TacacsConfigsCreateTacacsConfigData = {
    requestBody: TacacsConfigCreate;
};

export type TacacsConfigsCreateTacacsConfigResponse = (TacacsConfigPublic);

export type TacacsConfigsGeneratePreviewTacacsConfigResponse = (TacacsConfigPreviewPublic);

export type TacacsConfigsGetActiveTacacsConfigResponse = (TacacsConfigPublic);

export type TacacsConfigsReadTacacsConfigByIdData = {
    id: string;
};

export type TacacsConfigsReadTacacsConfigByIdResponse = (TacacsConfigPublic);

export type TacacsConfigsUpdateTacacsConfigData = {
    id: string;
    requestBody: TacacsConfigUpdate;
};

export type TacacsConfigsUpdateTacacsConfigResponse = (TacacsConfigPublic);

export type TacacsConfigsDeleteTacacsConfigData = {
    id: string;
};

export type TacacsConfigsDeleteTacacsConfigResponse = (Message);

export type TacacsConfigsCheckTacacsConfigByIdData = {
    id: string;
};

export type TacacsConfigsCheckTacacsConfigByIdResponse = (unknown);

export type TacacsGroupsReadTacacsGroupsData = {
    limit?: number;
    search?: (string | null);
    skip?: number;
};

export type TacacsGroupsReadTacacsGroupsResponse = (TacacsGroupsPublic);

export type TacacsGroupsCreateTacacsGroupData = {
    requestBody: TacacsGroupCreate;
};

export type TacacsGroupsCreateTacacsGroupResponse = (TacacsGroupPublic);

export type TacacsGroupsReadTacacsGroupByIdData = {
    id: string;
};

export type TacacsGroupsReadTacacsGroupByIdResponse = (TacacsGroupPublic);

export type TacacsGroupsUpdateTacacsGroupData = {
    id: string;
    requestBody: TacacsGroupUpdate;
};

export type TacacsGroupsUpdateTacacsGroupResponse = (TacacsGroupPublic);

export type TacacsGroupsDeleteTacacsGroupData = {
    id: string;
};

export type TacacsGroupsDeleteTacacsGroupResponse = (Message);

export type TacacsLogsGetLatestLogDateResponse = (TacacsLogLatestDate);

export type TacacsLogsGetLogEventsSummaryData = {
    date?: (string | null);
};

export type TacacsLogsGetLogEventsSummaryResponse = (TacacsLogDailySummary);

export type TacacsLogsListLogEventsData = {
    date?: (string | null);
    dateFrom?: (string | null);
    dateTo?: (string | null);
    limit?: number;
    logType?: string;
    nasIp?: (string | null);
    result?: (string | null);
    search?: (string | null);
    skip?: number;
    username?: (string | null);
};

export type TacacsLogsListLogEventsResponse = (TacacsLogEventsPublic);

export type TacacsLogsListLogFilesData = {
    limit?: number;
    search?: (string | null);
    skip?: number;
    sortBy?: string;
    sortOrder?: string;
};

export type TacacsLogsListLogFilesResponse = (TacacsLogsPublic);

export type TacacsLogsReadLogFileData = {
    id: string;
    search?: (string | null);
};

export type TacacsLogsReadLogFileResponse = (TacacsLogPublic);

export type TacacsNgSettingsReadTacacsNgSettingsResponse = (TacacsNgSettingPublic);

export type TacacsNgSettingsUpdateTacacsNgSettingsData = {
    requestBody: TacacsNgSettingUpdate;
};

export type TacacsNgSettingsUpdateTacacsNgSettingsResponse = (TacacsNgSettingPublic);

export type TacacsServicesReadTacacsServicesData = {
    limit?: number;
    search?: (string | null);
    skip?: number;
};

export type TacacsServicesReadTacacsServicesResponse = (TacacsServicesPublic);

export type TacacsServicesCreateTacacsServiceData = {
    requestBody: TacacsServiceCreate;
};

export type TacacsServicesCreateTacacsServiceResponse = (TacacsServicePublic);

export type TacacsServicesReadTacacsServiceByIdData = {
    id: string;
};

export type TacacsServicesReadTacacsServiceByIdResponse = (TacacsServicePublic);

export type TacacsServicesUpdateTacacsServiceData = {
    id: string;
    requestBody: TacacsServiceUpdate;
};

export type TacacsServicesUpdateTacacsServiceResponse = (TacacsServicePublic);

export type TacacsServicesDeleteTacacsServiceData = {
    id: string;
};

export type TacacsServicesDeleteTacacsServiceResponse = (Message);

export type TacacsUsersReadTacacsUsersData = {
    limit?: number;
    search?: (string | null);
    skip?: number;
};

export type TacacsUsersReadTacacsUsersResponse = (TacacsUsersPublic);

export type TacacsUsersCreateTacacsUserData = {
    requestBody: TacacsUserCreate;
};

export type TacacsUsersCreateTacacsUserResponse = (TacacsUserPublic);

export type TacacsUsersReadTacacsUserByIdData = {
    id: string;
};

export type TacacsUsersReadTacacsUserByIdResponse = (TacacsUserPublic);

export type TacacsUsersUpdateTacacsUserData = {
    id: string;
    requestBody: TacacsUserUpdate;
};

export type TacacsUsersUpdateTacacsUserResponse = (TacacsUserPublic);

export type TacacsUsersDeleteTacacsUserData = {
    id: string;
};

export type TacacsUsersDeleteTacacsUserResponse = (Message);

export type UsersReadUsersData = {
    limit?: number;
    search?: (string | null);
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);