"""add tacacs models

Revision ID: 097cd7afefc7
Revises: 1a31ce608336
Create Date: 2025-11-06 17:24:24.215005

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '097cd7afefc7'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('host',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('ipv4_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ipv6_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('secret_key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('welcome_banner', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reject_banner', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('motd_banner', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('failed_authentication_banner', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('parent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_host_name'), 'host', ['name'], unique=False)
    op.create_table('mavis',
    sa.Column('ldap_server_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ldap_hosts', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ldap_base', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ldap_user', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ldap_passwd', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ldap_filter', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ldap_timeout', sa.Integer(), nullable=False),
    sa.Column('require_tacacs_group_prefix', sa.Integer(), nullable=False),
    sa.Column('tacacs_group_prefix', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_action'), 'profile', ['action'], unique=False)
    op.create_index(op.f('ix_profile_name'), 'profile', ['name'], unique=True)
    op.create_table('ruleset',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('enabled', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ruleset_action'), 'ruleset', ['action'], unique=False)
    op.create_index(op.f('ix_ruleset_name'), 'ruleset', ['name'], unique=False)
    op.create_table('tacacsconfig',
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tacacsconfig_filename'), 'tacacsconfig', ['filename'], unique=True)
    op.create_table('tacacsgroup',
    sa.Column('group_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tacacsgroup_group_name'), 'tacacsgroup', ['group_name'], unique=False)
    op.create_table('tacacslog',
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('filepath', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tacacslog_filename'), 'tacacslog', ['filename'], unique=False)
    op.create_index(op.f('ix_tacacslog_filepath'), 'tacacslog', ['filepath'], unique=False)
    op.create_table('tacacsngsetting',
    sa.Column('ipv4_enabled', sa.Boolean(), nullable=False),
    sa.Column('ipv4_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ipv4_port', sa.Integer(), nullable=False),
    sa.Column('ipv6_enabled', sa.Boolean(), nullable=False),
    sa.Column('ipv6_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ipv6_port', sa.Integer(), nullable=False),
    sa.Column('instances_min', sa.Integer(), nullable=False),
    sa.Column('instances_max', sa.Integer(), nullable=False),
    sa.Column('background', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('access_logfile_destination', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('accounting_logfile_destination', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('authentication_logfile_destination', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('login_backend', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_backend', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pap_backend', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tacacsservice',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tacacsservice_name'), 'tacacsservice', ['name'], unique=False)
    op.create_table('tacacsuser',
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('password_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('member', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tacacsuser_member'), 'tacacsuser', ['member'], unique=False)
    op.create_index(op.f('ix_tacacsuser_password_type'), 'tacacsuser', ['password_type'], unique=False)
    op.create_index(op.f('ix_tacacsuser_username'), 'tacacsuser', ['username'], unique=True)
    op.create_table('profilescript',
    sa.Column('condition', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profilescript_action'), 'profilescript', ['action'], unique=False)
    op.create_index(op.f('ix_profilescript_condition'), 'profilescript', ['condition'], unique=False)
    op.create_index(op.f('ix_profilescript_key'), 'profilescript', ['key'], unique=False)
    op.create_index(op.f('ix_profilescript_value'), 'profilescript', ['value'], unique=False)
    op.create_table('rulesetscript',
    sa.Column('condition', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ruleset_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['ruleset_id'], ['ruleset.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rulesetscript_action'), 'rulesetscript', ['action'], unique=False)
    op.create_index(op.f('ix_rulesetscript_condition'), 'rulesetscript', ['condition'], unique=False)
    op.create_index(op.f('ix_rulesetscript_key'), 'rulesetscript', ['key'], unique=False)
    op.create_index(op.f('ix_rulesetscript_value'), 'rulesetscript', ['value'], unique=False)
    op.create_table('profilescriptset',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profilescript_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['profilescript_id'], ['profilescript.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profilescriptset_key'), 'profilescriptset', ['key'], unique=False)
    op.create_table('rulesetscriptset',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('rulesetscript_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['rulesetscript_id'], ['rulesetscript.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rulesetscriptset_key'), 'rulesetscriptset', ['key'], unique=False)
    op.create_index(op.f('ix_rulesetscriptset_value'), 'rulesetscriptset', ['value'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rulesetscriptset_value'), table_name='rulesetscriptset')
    op.drop_index(op.f('ix_rulesetscriptset_key'), table_name='rulesetscriptset')
    op.drop_table('rulesetscriptset')
    op.drop_index(op.f('ix_profilescriptset_key'), table_name='profilescriptset')
    op.drop_table('profilescriptset')
    op.drop_index(op.f('ix_rulesetscript_value'), table_name='rulesetscript')
    op.drop_index(op.f('ix_rulesetscript_key'), table_name='rulesetscript')
    op.drop_index(op.f('ix_rulesetscript_condition'), table_name='rulesetscript')
    op.drop_index(op.f('ix_rulesetscript_action'), table_name='rulesetscript')
    op.drop_table('rulesetscript')
    op.drop_index(op.f('ix_profilescript_value'), table_name='profilescript')
    op.drop_index(op.f('ix_profilescript_key'), table_name='profilescript')
    op.drop_index(op.f('ix_profilescript_condition'), table_name='profilescript')
    op.drop_index(op.f('ix_profilescript_action'), table_name='profilescript')
    op.drop_table('profilescript')
    op.drop_index(op.f('ix_tacacsuser_username'), table_name='tacacsuser')
    op.drop_index(op.f('ix_tacacsuser_password_type'), table_name='tacacsuser')
    op.drop_index(op.f('ix_tacacsuser_member'), table_name='tacacsuser')
    op.drop_table('tacacsuser')
    op.drop_index(op.f('ix_tacacsservice_name'), table_name='tacacsservice')
    op.drop_table('tacacsservice')
    op.drop_table('tacacsngsetting')
    op.drop_index(op.f('ix_tacacslog_filepath'), table_name='tacacslog')
    op.drop_index(op.f('ix_tacacslog_filename'), table_name='tacacslog')
    op.drop_table('tacacslog')
    op.drop_index(op.f('ix_tacacsgroup_group_name'), table_name='tacacsgroup')
    op.drop_table('tacacsgroup')
    op.drop_index(op.f('ix_tacacsconfig_filename'), table_name='tacacsconfig')
    op.drop_table('tacacsconfig')
    op.drop_index(op.f('ix_ruleset_name'), table_name='ruleset')
    op.drop_index(op.f('ix_ruleset_action'), table_name='ruleset')
    op.drop_table('ruleset')
    op.drop_index(op.f('ix_profile_name'), table_name='profile')
    op.drop_index(op.f('ix_profile_action'), table_name='profile')
    op.drop_table('profile')
    op.drop_table('mavis')
    op.drop_index(op.f('ix_host_name'), table_name='host')
    op.drop_table('host')
    # ### end Alembic commands ###
