"""add datetime

Revision ID: 40caa721e6a2
Revises: 097cd7afefc7
Create Date: 2025-11-07 17:12:59.619242

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '40caa721e6a2'
down_revision = '097cd7afefc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('host', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('item', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('mavis', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('profile', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('profilescript', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('profilescriptset', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('ruleset', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('rulesetscript', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('rulesetscriptset', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('tacacsconfig', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('tacacsgroup', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('tacacsngsetting', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('tacacsservice', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('tacacsuser', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created_at')
    op.drop_column('tacacsuser', 'created_at')
    op.drop_column('tacacsservice', 'created_at')
    op.drop_column('tacacsngsetting', 'created_at')
    op.drop_column('tacacsgroup', 'created_at')
    op.drop_column('tacacsconfig', 'created_at')
    op.drop_column('rulesetscriptset', 'created_at')
    op.drop_column('rulesetscript', 'created_at')
    op.drop_column('ruleset', 'created_at')
    op.drop_column('profilescriptset', 'created_at')
    op.drop_column('profilescript', 'created_at')
    op.drop_column('profile', 'created_at')
    op.drop_column('mavis', 'created_at')
    op.drop_column('item', 'created_at')
    op.drop_column('host', 'created_at')
    # ### end Alembic commands ###
