"""add statistics tables

Revision ID: 481620d2d694
Revises: a1551ca6df13
Create Date: 2025-12-12 15:29:57.754330

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '481620d2d694'
down_revision = 'a1551ca6df13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accountingstatistics',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('nas_ip', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('user_source_ip', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('start_count', sa.Integer(), nullable=False),
    sa.Column('stop_count', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accountingstatistics_nas_ip'), 'accountingstatistics', ['nas_ip'], unique=False)
    op.create_index(op.f('ix_accountingstatistics_user_source_ip'), 'accountingstatistics', ['user_source_ip'], unique=False)
    op.create_index(op.f('ix_accountingstatistics_username'), 'accountingstatistics', ['username'], unique=False)
    op.create_table('authenticationstatistics',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('nas_ip', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('user_source_ip', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('fail_count', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authenticationstatistics_nas_ip'), 'authenticationstatistics', ['nas_ip'], unique=False)
    op.create_index(op.f('ix_authenticationstatistics_user_source_ip'), 'authenticationstatistics', ['user_source_ip'], unique=False)
    op.create_index(op.f('ix_authenticationstatistics_username'), 'authenticationstatistics', ['username'], unique=False)
    op.create_table('authorizationstatistics',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('nas_ip', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('user_source_ip', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('permit_count', sa.Integer(), nullable=False),
    sa.Column('deny_count', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authorizationstatistics_nas_ip'), 'authorizationstatistics', ['nas_ip'], unique=False)
    op.create_index(op.f('ix_authorizationstatistics_user_source_ip'), 'authorizationstatistics', ['user_source_ip'], unique=False)
    op.create_index(op.f('ix_authorizationstatistics_username'), 'authorizationstatistics', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_authorizationstatistics_username'), table_name='authorizationstatistics')
    op.drop_index(op.f('ix_authorizationstatistics_user_source_ip'), table_name='authorizationstatistics')
    op.drop_index(op.f('ix_authorizationstatistics_nas_ip'), table_name='authorizationstatistics')
    op.drop_table('authorizationstatistics')
    op.drop_index(op.f('ix_authenticationstatistics_username'), table_name='authenticationstatistics')
    op.drop_index(op.f('ix_authenticationstatistics_user_source_ip'), table_name='authenticationstatistics')
    op.drop_index(op.f('ix_authenticationstatistics_nas_ip'), table_name='authenticationstatistics')
    op.drop_table('authenticationstatistics')
    op.drop_index(op.f('ix_accountingstatistics_username'), table_name='accountingstatistics')
    op.drop_index(op.f('ix_accountingstatistics_user_source_ip'), table_name='accountingstatistics')
    op.drop_index(op.f('ix_accountingstatistics_nas_ip'), table_name='accountingstatistics')
    op.drop_table('accountingstatistics')
    # ### end Alembic commands ###
