"""Add generate_config to models

Revision ID: 4ff49388474a
Revises: b0af430ec0d3
Create Date: 2026-06-19 15:46:46.838466

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4ff49388474a'
down_revision = 'b0af430ec0d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: ix_alertevent_triggered_at, ix_anomalydetectionresult_scored_at, and
    # ix_auditlog_entity_action_created were removed by autogenerate because they are
    # not declared via index=True in the model fields (they were created by explicit
    # op.create_index in earlier migrations). Preserving them here intentionally.
    op.add_column('host', sa.Column('generate_config', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.alter_column('notificationchannel', 'config_json',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.add_column('profile', sa.Column('generate_config', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('ruleset', sa.Column('generate_config', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('tacacsgroup', sa.Column('generate_config', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('tacacsservice', sa.Column('generate_config', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('tacacsuser', sa.Column('generate_config', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tacacsuser', 'generate_config')
    op.drop_column('tacacsservice', 'generate_config')
    op.drop_column('tacacsgroup', 'generate_config')
    op.drop_column('ruleset', 'generate_config')
    op.drop_column('profile', 'generate_config')
    op.alter_column('notificationchannel', 'config_json',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('host', 'generate_config')
    # ### end Alembic commands ###
