"""add ha_state table

Revision ID: 89abf27ed80c
Revises: 6eae04e1dc96
Create Date: 2026-06-26 19:57:24.691840

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '89abf27ed80c'
down_revision = 'e2f4856c5e86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hastate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_push_at', sa.DateTime(), nullable=True),
    sa.Column('last_received_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hastate')
    # ### end Alembic commands ###
