"""fix_webauthchallenge_expires_at_timezone

Revision ID: ee24f7a93c01
Revises: dd13bdaceafd
Create Date: 2026-04-18 12:42:00.000000

"""
from alembic import op
import sqlalchemy as sa

revision = 'ee24f7a93c01'
down_revision = 'dd13bdaceafd'
branch_labels = None
depends_on = None


def upgrade():
    # Fix timezone on expires_at (was incorrectly stripped by autogenerated migration)
    op.alter_column(
        'webauthchallenge',
        'expires_at',
        existing_type=sa.DateTime(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        postgresql_using="expires_at AT TIME ZONE 'UTC'",
    )
    # Add password_login_disabled if it was missing from an earlier broken migration run
    op.execute(
        "ALTER TABLE \"user\" ADD COLUMN IF NOT EXISTS "
        "password_login_disabled BOOLEAN NOT NULL DEFAULT FALSE"
    )


def downgrade():
    op.alter_column(
        'webauthchallenge',
        'expires_at',
        existing_type=sa.DateTime(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
    )
    op.drop_column('user', 'password_login_disabled')
