/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutTacacs_usersRouteImport } from './routes/_layout/tacacs_users'
import { Route as LayoutTacacs_servicesRouteImport } from './routes/_layout/tacacs_services'
import { Route as LayoutTacacs_ng_settingsRouteImport } from './routes/_layout/tacacs_ng_settings'
import { Route as LayoutTacacs_logsRouteImport } from './routes/_layout/tacacs_logs'
import { Route as LayoutTacacs_groupsRouteImport } from './routes/_layout/tacacs_groups'
import { Route as LayoutTacacs_configsRouteImport } from './routes/_layout/tacacs_configs'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutRulesetscriptsetsRouteImport } from './routes/_layout/rulesetscriptsets'
import { Route as LayoutRulesetscriptsRouteImport } from './routes/_layout/rulesetscripts'
import { Route as LayoutRulesetsRouteImport } from './routes/_layout/rulesets'
import { Route as LayoutProfilescriptsetsRouteImport } from './routes/_layout/profilescriptsets'
import { Route as LayoutProfilescriptsRouteImport } from './routes/_layout/profilescripts'
import { Route as LayoutProfilesRouteImport } from './routes/_layout/profiles'
import { Route as LayoutMavis_settingsRouteImport } from './routes/_layout/mavis_settings'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutHostsRouteImport } from './routes/_layout/hosts'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTacacs_usersRoute = LayoutTacacs_usersRouteImport.update({
  id: '/tacacs_users',
  path: '/tacacs_users',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTacacs_servicesRoute = LayoutTacacs_servicesRouteImport.update({
  id: '/tacacs_services',
  path: '/tacacs_services',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTacacs_ng_settingsRoute =
  LayoutTacacs_ng_settingsRouteImport.update({
    id: '/tacacs_ng_settings',
    path: '/tacacs_ng_settings',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutTacacs_logsRoute = LayoutTacacs_logsRouteImport.update({
  id: '/tacacs_logs',
  path: '/tacacs_logs',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTacacs_groupsRoute = LayoutTacacs_groupsRouteImport.update({
  id: '/tacacs_groups',
  path: '/tacacs_groups',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTacacs_configsRoute = LayoutTacacs_configsRouteImport.update({
  id: '/tacacs_configs',
  path: '/tacacs_configs',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRulesetscriptsetsRoute = LayoutRulesetscriptsetsRouteImport.update({
  id: '/rulesetscriptsets',
  path: '/rulesetscriptsets',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRulesetscriptsRoute = LayoutRulesetscriptsRouteImport.update({
  id: '/rulesetscripts',
  path: '/rulesetscripts',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRulesetsRoute = LayoutRulesetsRouteImport.update({
  id: '/rulesets',
  path: '/rulesets',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProfilescriptsetsRoute = LayoutProfilescriptsetsRouteImport.update({
  id: '/profilescriptsets',
  path: '/profilescriptsets',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProfilescriptsRoute = LayoutProfilescriptsRouteImport.update({
  id: '/profilescripts',
  path: '/profilescripts',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProfilesRoute = LayoutProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMavis_settingsRoute = LayoutMavis_settingsRouteImport.update({
  id: '/mavis_settings',
  path: '/mavis_settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutHostsRoute = LayoutHostsRouteImport.update({
  id: '/hosts',
  path: '/hosts',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/hosts': typeof LayoutHostsRoute
  '/items': typeof LayoutItemsRoute
  '/mavis_settings': typeof LayoutMavis_settingsRoute
  '/profiles': typeof LayoutProfilesRoute
  '/profilescripts': typeof LayoutProfilescriptsRoute
  '/profilescriptsets': typeof LayoutProfilescriptsetsRoute
  '/rulesets': typeof LayoutRulesetsRoute
  '/rulesetscripts': typeof LayoutRulesetscriptsRoute
  '/rulesetscriptsets': typeof LayoutRulesetscriptsetsRoute
  '/settings': typeof LayoutSettingsRoute
  '/tacacs_configs': typeof LayoutTacacs_configsRoute
  '/tacacs_groups': typeof LayoutTacacs_groupsRoute
  '/tacacs_logs': typeof LayoutTacacs_logsRoute
  '/tacacs_ng_settings': typeof LayoutTacacs_ng_settingsRoute
  '/tacacs_services': typeof LayoutTacacs_servicesRoute
  '/tacacs_users': typeof LayoutTacacs_usersRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/hosts': typeof LayoutHostsRoute
  '/items': typeof LayoutItemsRoute
  '/mavis_settings': typeof LayoutMavis_settingsRoute
  '/profiles': typeof LayoutProfilesRoute
  '/profilescripts': typeof LayoutProfilescriptsRoute
  '/profilescriptsets': typeof LayoutProfilescriptsetsRoute
  '/rulesets': typeof LayoutRulesetsRoute
  '/rulesetscripts': typeof LayoutRulesetscriptsRoute
  '/rulesetscriptsets': typeof LayoutRulesetscriptsetsRoute
  '/settings': typeof LayoutSettingsRoute
  '/tacacs_configs': typeof LayoutTacacs_configsRoute
  '/tacacs_groups': typeof LayoutTacacs_groupsRoute
  '/tacacs_logs': typeof LayoutTacacs_logsRoute
  '/tacacs_ng_settings': typeof LayoutTacacs_ng_settingsRoute
  '/tacacs_services': typeof LayoutTacacs_servicesRoute
  '/tacacs_users': typeof LayoutTacacs_usersRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/hosts': typeof LayoutHostsRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/mavis_settings': typeof LayoutMavis_settingsRoute
  '/_layout/profiles': typeof LayoutProfilesRoute
  '/_layout/profilescripts': typeof LayoutProfilescriptsRoute
  '/_layout/profilescriptsets': typeof LayoutProfilescriptsetsRoute
  '/_layout/rulesets': typeof LayoutRulesetsRoute
  '/_layout/rulesetscripts': typeof LayoutRulesetscriptsRoute
  '/_layout/rulesetscriptsets': typeof LayoutRulesetscriptsetsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/tacacs_configs': typeof LayoutTacacs_configsRoute
  '/_layout/tacacs_groups': typeof LayoutTacacs_groupsRoute
  '/_layout/tacacs_logs': typeof LayoutTacacs_logsRoute
  '/_layout/tacacs_ng_settings': typeof LayoutTacacs_ng_settingsRoute
  '/_layout/tacacs_services': typeof LayoutTacacs_servicesRoute
  '/_layout/tacacs_users': typeof LayoutTacacs_usersRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/hosts'
    | '/items'
    | '/mavis_settings'
    | '/profiles'
    | '/profilescripts'
    | '/profilescriptsets'
    | '/rulesets'
    | '/rulesetscripts'
    | '/rulesetscriptsets'
    | '/settings'
    | '/tacacs_configs'
    | '/tacacs_groups'
    | '/tacacs_logs'
    | '/tacacs_ng_settings'
    | '/tacacs_services'
    | '/tacacs_users'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/hosts'
    | '/items'
    | '/mavis_settings'
    | '/profiles'
    | '/profilescripts'
    | '/profilescriptsets'
    | '/rulesets'
    | '/rulesetscripts'
    | '/rulesetscriptsets'
    | '/settings'
    | '/tacacs_configs'
    | '/tacacs_groups'
    | '/tacacs_logs'
    | '/tacacs_ng_settings'
    | '/tacacs_services'
    | '/tacacs_users'
    | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/hosts'
    | '/_layout/items'
    | '/_layout/mavis_settings'
    | '/_layout/profiles'
    | '/_layout/profilescripts'
    | '/_layout/profilescriptsets'
    | '/_layout/rulesets'
    | '/_layout/rulesetscripts'
    | '/_layout/rulesetscriptsets'
    | '/_layout/settings'
    | '/_layout/tacacs_configs'
    | '/_layout/tacacs_groups'
    | '/_layout/tacacs_logs'
    | '/_layout/tacacs_ng_settings'
    | '/_layout/tacacs_services'
    | '/_layout/tacacs_users'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tacacs_users': {
      id: '/_layout/tacacs_users'
      path: '/tacacs_users'
      fullPath: '/tacacs_users'
      preLoaderRoute: typeof LayoutTacacs_usersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tacacs_services': {
      id: '/_layout/tacacs_services'
      path: '/tacacs_services'
      fullPath: '/tacacs_services'
      preLoaderRoute: typeof LayoutTacacs_servicesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tacacs_ng_settings': {
      id: '/_layout/tacacs_ng_settings'
      path: '/tacacs_ng_settings'
      fullPath: '/tacacs_ng_settings'
      preLoaderRoute: typeof LayoutTacacs_ng_settingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tacacs_logs': {
      id: '/_layout/tacacs_logs'
      path: '/tacacs_logs'
      fullPath: '/tacacs_logs'
      preLoaderRoute: typeof LayoutTacacs_logsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tacacs_groups': {
      id: '/_layout/tacacs_groups'
      path: '/tacacs_groups'
      fullPath: '/tacacs_groups'
      preLoaderRoute: typeof LayoutTacacs_groupsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tacacs_configs': {
      id: '/_layout/tacacs_configs'
      path: '/tacacs_configs'
      fullPath: '/tacacs_configs'
      preLoaderRoute: typeof LayoutTacacs_configsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/rulesetscriptsets': {
      id: '/_layout/rulesetscriptsets'
      path: '/rulesetscriptsets'
      fullPath: '/rulesetscriptsets'
      preLoaderRoute: typeof LayoutRulesetscriptsetsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/rulesetscripts': {
      id: '/_layout/rulesetscripts'
      path: '/rulesetscripts'
      fullPath: '/rulesetscripts'
      preLoaderRoute: typeof LayoutRulesetscriptsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/rulesets': {
      id: '/_layout/rulesets'
      path: '/rulesets'
      fullPath: '/rulesets'
      preLoaderRoute: typeof LayoutRulesetsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/profilescriptsets': {
      id: '/_layout/profilescriptsets'
      path: '/profilescriptsets'
      fullPath: '/profilescriptsets'
      preLoaderRoute: typeof LayoutProfilescriptsetsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/profilescripts': {
      id: '/_layout/profilescripts'
      path: '/profilescripts'
      fullPath: '/profilescripts'
      preLoaderRoute: typeof LayoutProfilescriptsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/profiles': {
      id: '/_layout/profiles'
      path: '/profiles'
      fullPath: '/profiles'
      preLoaderRoute: typeof LayoutProfilesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/mavis_settings': {
      id: '/_layout/mavis_settings'
      path: '/mavis_settings'
      fullPath: '/mavis_settings'
      preLoaderRoute: typeof LayoutMavis_settingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/hosts': {
      id: '/_layout/hosts'
      path: '/hosts'
      fullPath: '/hosts'
      preLoaderRoute: typeof LayoutHostsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutHostsRoute: typeof LayoutHostsRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutMavis_settingsRoute: typeof LayoutMavis_settingsRoute
  LayoutProfilesRoute: typeof LayoutProfilesRoute
  LayoutProfilescriptsRoute: typeof LayoutProfilescriptsRoute
  LayoutProfilescriptsetsRoute: typeof LayoutProfilescriptsetsRoute
  LayoutRulesetsRoute: typeof LayoutRulesetsRoute
  LayoutRulesetscriptsRoute: typeof LayoutRulesetscriptsRoute
  LayoutRulesetscriptsetsRoute: typeof LayoutRulesetscriptsetsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutTacacs_configsRoute: typeof LayoutTacacs_configsRoute
  LayoutTacacs_groupsRoute: typeof LayoutTacacs_groupsRoute
  LayoutTacacs_logsRoute: typeof LayoutTacacs_logsRoute
  LayoutTacacs_ng_settingsRoute: typeof LayoutTacacs_ng_settingsRoute
  LayoutTacacs_servicesRoute: typeof LayoutTacacs_servicesRoute
  LayoutTacacs_usersRoute: typeof LayoutTacacs_usersRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutHostsRoute: LayoutHostsRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutMavis_settingsRoute: LayoutMavis_settingsRoute,
  LayoutProfilesRoute: LayoutProfilesRoute,
  LayoutProfilescriptsRoute: LayoutProfilescriptsRoute,
  LayoutProfilescriptsetsRoute: LayoutProfilescriptsetsRoute,
  LayoutRulesetsRoute: LayoutRulesetsRoute,
  LayoutRulesetscriptsRoute: LayoutRulesetscriptsRoute,
  LayoutRulesetscriptsetsRoute: LayoutRulesetscriptsetsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutTacacs_configsRoute: LayoutTacacs_configsRoute,
  LayoutTacacs_groupsRoute: LayoutTacacs_groupsRoute,
  LayoutTacacs_logsRoute: LayoutTacacs_logsRoute,
  LayoutTacacs_ng_settingsRoute: LayoutTacacs_ng_settingsRoute,
  LayoutTacacs_servicesRoute: LayoutTacacs_servicesRoute,
  LayoutTacacs_usersRoute: LayoutTacacs_usersRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
