name: Test Backend

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:

jobs:
  test-backend:
    runs-on: ubuntu-latest
    env:
      POSTGRES_SERVER: localhost
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fixed_password_for_tests
      POSTGRES_DB: app
      SECRET_KEY: fixed_secret_key_for_tests_1234567890
      FIRST_SUPERUSER: admin@example.com
      FIRST_SUPERUSER_PASSWORD: fixed_admin_password_123
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.11"
          enable-cache: true
      - name: Sync dependencies
        run: uv sync
        working-directory: backend
      - run: docker compose down -v --remove-orphans
      - run: docker compose up -d db mailcatcher
      - name: Wait for DB
        run: |
          until docker compose exec db pg_isready -U postgres; do sleep 1; done
        working-directory: backend
      - name: Migrate DB
        run: uv run bash scripts/prestart.sh
        working-directory: backend
      - name: Run tests
        run: uv run bash scripts/tests-start.sh "Coverage for ${{ github.sha }}"
        working-directory: backend
      - run: docker compose down -v --remove-orphans
      - name: Store coverage files
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: backend/htmlcov
          include-hidden-files: true
